package FacturasXML;

import BaseDeDatos.*;
import Clases.*;
import Formularios.BD;
import Formularios.Login;
import com.toedter.calendar.JDateChooser;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

public class FRM_MPFactura extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    String Ruta = "";
    BD mBD = new BD();
    BD dao = null;
    Tabla_PdfVO tpdf = new Tabla_PdfVO();
    int Seleccion;
    int SeleccionY;
    
    public static String Cantidad;
    public static String PrecioUnitario;
    public static String PrecioTotal;
    public static String Descripcion;
    public static String UnidadMedida;
    public static Date FechaFactura;
    public static int idFactura;

    public FRM_MPFactura() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cotizador Encinales");

        TxtClave.setText("-" + UnidadMedida + FechaFactura.getMonth() + FechaFactura.getDay());
        TxtCant.setText(String.valueOf(Integer.parseInt(Cantidad.substring(0, Cantidad.indexOf('.')))));
        TxtPrecio.setText(PrecioUnitario);
        TxtDes.setText(Descripcion);
        TxtMedida.setText(UnidadMedida);
        TXT_PrecioCorte.setText("0");
        TXT_PrecioDobles.setText("0");
        TXT_PrecioRoscado.setText("0");
        TXT_PrecioSoldadura.setText("0");
        LblProceso.setText("");
        jLabel15.setText("De la fecha " + FechaFactura);
        jLabel16.setText("");
        jLabel19.setText("");
        jLabel20.setText("");
        evitarPegar(this.TxtCant);
        evitarPegar(this.TxtClave);
        evitarPegar(this.TxtDes);
        evitarPegar(this.TxtMedida);
        evitarPegar(this.TxtPrecio);
        RB_No.setSelected(true);
        RB_Si.setSelected(false);
        
        if (RB_No.isSelected() == true && RB_Si.isSelected() == false)
        {
            TXT_PrecioCorte.setText("0");
            TXT_PrecioDobles.setText("0");
            TXT_PrecioRoscado.setText("0");
            TXT_PrecioSoldadura.setText("0");
            TXT_PrecioCorte.setEnabled(false);
            TXT_PrecioDobles.setEnabled(false);
            TXT_PrecioRoscado.setEnabled(false);
            TXT_PrecioSoldadura.setEnabled(false);
        }
        else
        {
            TXT_PrecioCorte.setEnabled(true);
            TXT_PrecioDobles.setEnabled(true);
            TXT_PrecioRoscado.setEnabled(true);
            TXT_PrecioSoldadura.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtClave = new javax.swing.JTextField();
        TxtDes = new javax.swing.JTextField();
        TxtCant = new javax.swing.JTextField();
        TxtMedida = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        LblProceso = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXT_PrecioCorte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TXT_PrecioDobles = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_PrecioRoscado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TXT_PrecioSoldadura = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        RB_Si = new javax.swing.JRadioButton();
        RB_No = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        jLabel5.setText("jLabel5");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 0, 28)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cuenta (1).png"))); // NOI18N
        jLabel2.setText("Añadir Compra");

        BtnSave.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnSave.setText("Agregar a Compras");
        BtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSaveMouseClicked(evt);
            }
        });
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel8.setText("Clave");

        jLabel9.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel9.setText("Descripción ");

        jLabel10.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel10.setText("Cantidad");

        jLabel11.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel11.setText("Unidad de Medida");

        jLabel12.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel12.setText("Precio Total ");

        TxtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtClaveKeyTyped(evt);
            }
        });

        TxtDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDesKeyTyped(evt);
            }
        });

        TxtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCantKeyTyped(evt);
            }
        });

        TxtMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMedidaActionPerformed(evt);
            }
        });
        TxtMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMedidaKeyTyped(evt);
            }
        });

        TxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrecioKeyTyped(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/003.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Sukhumvit Set", 0, 24)); // NOI18N
        jLabel13.setText("Añadir Datos");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("jLabel16");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("jLabel19");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("jLabel20");

        jLabel15.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel15.setText("De la fecha ....");

        jLabel3.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel3.setText("¿Es cotizable?");

        TXT_PrecioCorte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_PrecioCorteKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel4.setText("Precio de Dobles:");

        TXT_PrecioDobles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_PrecioDoblesKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel7.setText("Precio de Roscado:");

        TXT_PrecioRoscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_PrecioRoscadoKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel14.setText("Precio de Soldadura:");

        TXT_PrecioSoldadura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_PrecioSoldaduraKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel17.setText("Precio de Corte:");

        buttonGroup1.add(RB_Si);
        RB_Si.setText("Si");
        RB_Si.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB_SiMouseClicked(evt);
            }
        });
        RB_Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_SiActionPerformed(evt);
            }
        });

        buttonGroup1.add(RB_No);
        RB_No.setText("No");
        RB_No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB_NoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addComponent(TxtClave)
                                    .addComponent(TxtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(TxtMedida, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12))
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel19)
                                            .addComponent(TxtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                            .addComponent(TxtDes))))))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_PrecioSoldadura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_PrecioRoscado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(TXT_PrecioDobles, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RB_Si)
                                        .addGap(18, 18, 18)
                                        .addComponent(RB_No))
                                    .addComponent(TXT_PrecioCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(RB_Si)
                            .addComponent(RB_No))))
                .addGap(2, 2, 2)
                .addComponent(jLabel16)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_PrecioCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TXT_PrecioDobles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(TXT_PrecioSoldadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TXT_PrecioRoscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSaveMouseClicked
        // TODO add your handling code here:
        if (!this.TxtCant.getText().isEmpty() || !this.TxtDes.getText().isEmpty() || !this.TxtClave.getText().isEmpty()
                || !this.TxtMedida.getText().isEmpty() || !this.TxtPrecio.getText().isEmpty())
        {
            int Cant = 0;
            String Des = "";
            String Clave = "";
            String UMedida = "";
            float Precio = 0;
            Date Fecha = null;

            Cant = Integer.parseInt(TxtCant.getText());
            Des = TxtDes.getText();
            Clave = this.TxtClave.getText();
            UMedida = TxtMedida.getText();
            Precio = Float.parseFloat(TxtPrecio.getText());               
            
            BD BDT = new BD();
            BD_1 mBD = new BD_1();
            
            ClaseCompras Com = new ClaseCompras();
            Com.setCantidad(Cant);
            Com.setClave(Clave);
            Com.setDescripcion(Des);
            Com.setPrecio(Precio);
            Com.setUMedida(UMedida);
            Com.setIdFactura(idFactura);
            Fecha = FechaFactura;
            Com.setFecha(Fecha);
            
            MateriaCotizable mMC = new MateriaCotizable();
            mMC.setClave(Clave);
            mMC.setDescripcion(Des);
            mMC.setPrecioCorte(Double.parseDouble(TXT_PrecioCorte.getText()));
            mMC.setPrecioDobles(Double.parseDouble(TXT_PrecioDobles.getText()));
            mMC.setPrecioRoscado(Double.parseDouble(TXT_PrecioRoscado.getText()));
            mMC.setPrecioSoldadura(Double.parseDouble(TXT_PrecioSoldadura.getText()));
            mMC.setPrecioUnitario(Precio);
            
            if (BDT.Agregar_Compra(Com)) {
                TxtCant.setText("");
                TxtDes.setText("");
                TxtClave.setText("");
                TxtMedida.setText("");
                TxtPrecio.setText("");
                JOptionPane.showMessageDialog(null, "Compra agregada con Exito");
                this.setVisible(false);
                
                String DescripcionN = "El usuario " + Login.NombreUsuario + " agregó una compra de materia prima";
                mBD.AgregarRegistro(DescripcionN);
                mBD.Desconectar();
                
                if (RB_No.isSelected() == true && RB_Si.isSelected() == false)
                {
                   
                }
                else
                {
                    mBD.AgregarMateriaPrimaCotizable(mMC);
                    DescripcionN = "El usuario " + Login.NombreUsuario + " agregó una compra de materia prima cotizable";
                    mBD.AgregarRegistro(DescripcionN);
                    mBD.Desconectar();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No a llenado todos los elementos");
        }
    }//GEN-LAST:event_BtnSaveMouseClicked

    private void TxtClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtClaveKeyTyped
        // TODO add your handling code here:
        if ((this.TxtClave.getText().length() == 45)) {
            evt.consume();

        } else if (this.TxtClave.getText().length() < 3) {
            jLabel16.setText("Demasiado pequeña");
        } else if (this.TxtClave.getText().length() >= 3) {
            this.jLabel16.setText("");
        }

    }//GEN-LAST:event_TxtClaveKeyTyped

    private void TxtDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDesKeyTyped
        // TODO add your handling code here:

        if (TxtDes.getText().length() == 45) {
            evt.consume();
        } else if (TxtDes.getText().length() < 5) {
            jLabel19.setText("Demasiado pequeña");
        } else if (TxtDes.getText().length() >= 5) {
            this.jLabel19.setText("");
        }
    }//GEN-LAST:event_TxtDesKeyTyped

    private void TxtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioKeyTyped
        // TODO add your handling code here:
       char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TxtPrecio.getText().length() == 10) {
            evt.consume();
        }
        
        if (evt.getKeyChar() == '.' && TxtPrecio.getText().contains(".")) {
            evt.consume();
        }
        
        if (evt.getKeyChar() == ' ') {
            
        }
    }//GEN-LAST:event_TxtPrecioKeyTyped

    private void TxtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantKeyTyped

      char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TxtCant.getText().length() == 10) {
            evt.consume();
        }
        
        if (evt.getKeyChar() == '.' && TxtCant.getText().contains(".")) {
            evt.consume();
        }
       
        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TxtCantKeyTyped

    private void TxtMedidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMedidaKeyTyped
        // TODO add your handling code here:
        if (TxtMedida.getText().length() == 45) {
            evt.consume();
        }  else if (TxtMedida.getText().length() < 2) {
            jLabel20.setText("Demasiado pequeña");
        } else if (TxtMedida.getText().length() >= 2) {
            this.jLabel20.setText("");
        }
    }//GEN-LAST:event_TxtMedidaKeyTyped

    private void TxtMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMedidaActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void TXT_PrecioCorteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_PrecioCorteKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_PrecioCorte.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '@' && TXT_PrecioCorte.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_PrecioCorteKeyTyped

    private void TXT_PrecioDoblesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_PrecioDoblesKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_PrecioDobles.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '@' && TXT_PrecioDobles.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_PrecioDoblesKeyTyped

    private void TXT_PrecioRoscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_PrecioRoscadoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_PrecioDobles.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '@' && TXT_PrecioDobles.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_PrecioRoscadoKeyTyped

    private void TXT_PrecioSoldaduraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_PrecioSoldaduraKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.'))
        {
            evt.consume();
        }

        if (TXT_PrecioDobles.getText().length() == 10)
        {
            evt.consume();
        }

        if (evt.getKeyChar() == '@' && TXT_PrecioDobles.getText().contains("."))
        {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_PrecioSoldaduraKeyTyped

    private void RB_SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_SiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_SiActionPerformed

    private void RB_NoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB_NoMouseClicked
        // TODO add your handling code here:
        if (RB_No.isSelected() == true && RB_Si.isSelected() == false)
        {
            TXT_PrecioCorte.setText("0");
            TXT_PrecioDobles.setText("0");
            TXT_PrecioRoscado.setText("0");
            TXT_PrecioSoldadura.setText("0");
            TXT_PrecioCorte.setEnabled(false);
            TXT_PrecioDobles.setEnabled(false);
            TXT_PrecioRoscado.setEnabled(false);
            TXT_PrecioSoldadura.setEnabled(false);
        }
        else
        {            
            TXT_PrecioCorte.setEnabled(true);
            TXT_PrecioDobles.setEnabled(true);
            TXT_PrecioRoscado.setEnabled(true);
            TXT_PrecioSoldadura.setEnabled(true);
        }
    }//GEN-LAST:event_RB_NoMouseClicked

    private void RB_SiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB_SiMouseClicked
        // TODO add your handling code here:
        if (RB_No.isSelected() == true && RB_Si.isSelected() == false)
        {
            TXT_PrecioCorte.setText("0");
            TXT_PrecioDobles.setText("0");
            TXT_PrecioRoscado.setText("0");
            TXT_PrecioSoldadura.setText("0");
            TXT_PrecioCorte.setEnabled(false);
            TXT_PrecioDobles.setEnabled(false);
            TXT_PrecioRoscado.setEnabled(false);
            TXT_PrecioSoldadura.setEnabled(false);
        }
        else
        {
            TXT_PrecioCorte.setEnabled(true);
            TXT_PrecioDobles.setEnabled(true);
            TXT_PrecioRoscado.setEnabled(true);
            TXT_PrecioSoldadura.setEnabled(true);
        }
    }//GEN-LAST:event_RB_SiMouseClicked

    private static java.sql.Date convert(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }

    public static void evitarPegar(JTextField campo) {

        InputMap map2 = campo.getInputMap(JTextField.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

    }

    public static void evitarPegar(JDateChooser campo) {

        InputMap map2 = campo.getInputMap(JDateChooser.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MPFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MPFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MPFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MPFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MPFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel LblProceso;
    private javax.swing.JRadioButton RB_No;
    private javax.swing.JRadioButton RB_Si;
    private javax.swing.JTextField TXT_PrecioCorte;
    private javax.swing.JTextField TXT_PrecioDobles;
    private javax.swing.JTextField TXT_PrecioRoscado;
    private javax.swing.JTextField TXT_PrecioSoldadura;
    private javax.swing.JTextField TxtCant;
    private javax.swing.JTextField TxtClave;
    private javax.swing.JTextField TxtDes;
    private javax.swing.JTextField TxtMedida;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
