/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author manuelvaquera
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAdminComparacion = new javax.swing.JButton();
        BtnAdminUsuarios = new javax.swing.JButton();
        BtnAdminFacturas = new javax.swing.JButton();
        BtnAdminCotizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnAdminProductos = new javax.swing.JButton();
        BtnAdminSalirMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnAdminComparacion.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        BtnAdminComparacion.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnAdminComparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/documento.png"))); // NOI18N
        BtnAdminComparacion.setText("Comparar Precio");
        BtnAdminComparacion.setBorderPainted(false);
        BtnAdminComparacion.setContentAreaFilled(false);
        BtnAdminComparacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdminComparacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAdminComparacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/documento (1).png"))); // NOI18N
        BtnAdminComparacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/documento (1).png"))); // NOI18N
        BtnAdminComparacion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnAdminComparacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAdminComparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminComparacionActionPerformed(evt);
            }
        });

        BtnAdminUsuarios.setBackground(new java.awt.Color(238, 217, 158));
        BtnAdminUsuarios.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnAdminUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tarjeta (1).png"))); // NOI18N
        BtnAdminUsuarios.setText("Usuarios");
        BtnAdminUsuarios.setBorderPainted(false);
        BtnAdminUsuarios.setContentAreaFilled(false);
        BtnAdminUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdminUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAdminUsuarios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tarjeta.png"))); // NOI18N
        BtnAdminUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tarjeta.png"))); // NOI18N
        BtnAdminUsuarios.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnAdminUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnAdminFacturas.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnAdminFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/proyecto-de-ley.png"))); // NOI18N
        BtnAdminFacturas.setText("Facturas");
        BtnAdminFacturas.setBorderPainted(false);
        BtnAdminFacturas.setContentAreaFilled(false);
        BtnAdminFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdminFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAdminFacturas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/proyecto-de-ley (1).png"))); // NOI18N
        BtnAdminFacturas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/proyecto-de-ley (1).png"))); // NOI18N
        BtnAdminFacturas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/proyecto-de-ley (1).png"))); // NOI18N
        BtnAdminFacturas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAdminFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminFacturasActionPerformed(evt);
            }
        });

        BtnAdminCotizar.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnAdminCotizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tutorial.png"))); // NOI18N
        BtnAdminCotizar.setText("Cotizar");
        BtnAdminCotizar.setBorderPainted(false);
        BtnAdminCotizar.setContentAreaFilled(false);
        BtnAdminCotizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdminCotizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAdminCotizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tutorial (2).png"))); // NOI18N
        BtnAdminCotizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tutorial (2).png"))); // NOI18N
        BtnAdminCotizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAdminCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminCotizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido Administrador");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logotipo encinales _1.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salida.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 0, 24)); // NOI18N
        jLabel2.setText("Seleccione Alguna de las Siguientes Opciones");

        BtnAdminProductos.setBackground(new java.awt.Color(0, 102, 102));
        BtnAdminProductos.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnAdminProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lista-de-quehaceres.png"))); // NOI18N
        BtnAdminProductos.setText("Productos ");
        BtnAdminProductos.setBorderPainted(false);
        BtnAdminProductos.setContentAreaFilled(false);
        BtnAdminProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdminProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAdminProductos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lista-de-quehaceres (1).png"))); // NOI18N
        BtnAdminProductos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lista-de-quehaceres (1).png"))); // NOI18N
        BtnAdminProductos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnAdminProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAdminProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminProductosActionPerformed(evt);
            }
        });

        BtnAdminSalirMenu.setBackground(new java.awt.Color(255, 255, 255));
        BtnAdminSalirMenu.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtnAdminSalirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (1).png"))); // NOI18N
        BtnAdminSalirMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAdminSalirMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (2).png"))); // NOI18N
        BtnAdminSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminSalirMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(42, 42, 42)
                        .addComponent(BtnAdminUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtnAdminProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAdminSalirMenu)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(BtnAdminComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAdminCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtnAdminFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnAdminSalirMenu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnAdminComparacion, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnAdminFacturas))
                    .addComponent(BtnAdminCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAdminUsuarios)
                            .addComponent(BtnAdminProductos))
                        .addGap(27, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdminProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdminProductosActionPerformed

    private void BtnAdminCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminCotizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdminCotizarActionPerformed

    private void BtnAdminComparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminComparacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdminComparacionActionPerformed

    private void BtnAdminFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdminFacturasActionPerformed

    private void BtnAdminSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminSalirMenuActionPerformed
            
               Login mLogin = new Login();
               this.dispose();
               mLogin.setVisible(true);
    }//GEN-LAST:event_BtnAdminSalirMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdminComparacion;
    private javax.swing.JButton BtnAdminCotizar;
    private javax.swing.JButton BtnAdminFacturas;
    private javax.swing.JButton BtnAdminProductos;
    private javax.swing.JButton BtnAdminSalirMenu;
    private javax.swing.JButton BtnAdminUsuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
