/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Formularios.Comparacion.*;
import Formularios.Cotizacion.*;
import Formularios.CotizacionPrevia.*;

/**
 *
 * @author manuelvaquera
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cotizador Encinales");
        BtnVentasCotizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnVentasCotizar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnVentasCotizar = new javax.swing.JButton();
        BtnVentasComparacion = new javax.swing.JButton();
        BtnVentasSalirMenu = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/003.jpg"))); // NOI18N

        BtnVentasCotizar2.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnVentasCotizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reporte (2).png"))); // NOI18N
        BtnVentasCotizar2.setText("Cotización Preliminar ");
        BtnVentasCotizar2.setBorderPainted(false);
        BtnVentasCotizar2.setContentAreaFilled(false);
        BtnVentasCotizar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVentasCotizar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reporte (4).png"))); // NOI18N
        BtnVentasCotizar2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reporte (4).png"))); // NOI18N
        BtnVentasCotizar2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reporte (4).png"))); // NOI18N
        BtnVentasCotizar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnVentasCotizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVentasCotizar2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido Encargado de Ventas ");

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 0, 24)); // NOI18N
        jLabel2.setText("Seleccione alguna de las siguientes opciones");

        BtnVentasCotizar.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnVentasCotizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tutorial.png"))); // NOI18N
        BtnVentasCotizar.setText("Cotización General");
        BtnVentasCotizar.setBorderPainted(false);
        BtnVentasCotizar.setContentAreaFilled(false);
        BtnVentasCotizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVentasCotizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVentasCotizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tutorial (2).png"))); // NOI18N
        BtnVentasCotizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tutorial (2).png"))); // NOI18N
        BtnVentasCotizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnVentasCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasCotizarActionPerformed(evt);
            }
        });

        BtnVentasComparacion.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        BtnVentasComparacion.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BtnVentasComparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/documento.png"))); // NOI18N
        BtnVentasComparacion.setText("Comparar Precio");
        BtnVentasComparacion.setBorderPainted(false);
        BtnVentasComparacion.setContentAreaFilled(false);
        BtnVentasComparacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVentasComparacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVentasComparacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/documento (1).png"))); // NOI18N
        BtnVentasComparacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/documento (1).png"))); // NOI18N
        BtnVentasComparacion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnVentasComparacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnVentasComparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasComparacionActionPerformed(evt);
            }
        });

        BtnVentasSalirMenu.setBackground(new java.awt.Color(255, 255, 255));
        BtnVentasSalirMenu.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        BtnVentasSalirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (3).png"))); // NOI18N
        BtnVentasSalirMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnVentasSalirMenu.setBorderPainted(false);
        BtnVentasSalirMenu.setContentAreaFilled(false);
        BtnVentasSalirMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (1).png"))); // NOI18N
        BtnVentasSalirMenu.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (1).png"))); // NOI18N
        BtnVentasSalirMenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (1).png"))); // NOI18N
        BtnVentasSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasSalirMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnVentasSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(BtnVentasCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnVentasComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1))
                            .addComponent(BtnVentasCotizar2))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVentasSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnVentasComparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVentasCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BtnVentasCotizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVentasCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasCotizarActionPerformed
        // TODO add your handling code here:
        ElegirProducto mEP = new ElegirProducto();
        mEP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVentasCotizarActionPerformed

    private void BtnVentasComparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasComparacionActionPerformed
        // TODO add your handling code here:
        ComparacionPrecios mCP = new ComparacionPrecios();
        mCP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVentasComparacionActionPerformed

    private void BtnVentasSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasSalirMenuActionPerformed

        Login mLogin = new Login();
        this.dispose();
        mLogin.setVisible(true);
    }//GEN-LAST:event_BtnVentasSalirMenuActionPerformed

    private void BtnVentasCotizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVentasCotizar2MouseClicked
        // TODO add your handling code here:
        CotizacionPrevia mCP = new CotizacionPrevia();
        mCP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVentasCotizar2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVentasComparacion;
    private javax.swing.JButton BtnVentasCotizar;
    private javax.swing.JButton BtnVentasCotizar2;
    private javax.swing.JButton BtnVentasSalirMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
