/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Comparacion;

import BaseDeDatos.*;
import Clases.*;
import Formularios.*;
import java.awt.Image;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author eduardogarciadelgado
 */
public class ComparacionPrecios extends javax.swing.JFrame {

    /**
     * Creates new form ComparacionPrecios
     */
    Competencia mC;
    BD_1 mBD;
    Producto mProducto;
    ComparacionPrecios_1 mCP_1;
    
    DefaultTableModel TablaProductoEncinales;
    DefaultTableModel TablaCompetencia;
    
    String ClaveProducto;
    int Seleccion;
    double PrecioProducto;
    ArrayList PreciosCompetencia;
    
    DecimalFormat mDF;
    
    public ComparacionPrecios() 
    {
        TablaProductoEncinales = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column) 
            {
                return false;
            }
        };
        TablaCompetencia = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column) 
            {
                return false;
            }
        };
        
        initComponents();        
        TablaProductoEncinales.addColumn("Clave");
        TablaProductoEncinales.addColumn("Nombre");
        TablaProductoEncinales.addColumn("Descripción");
        TablaProductoEncinales.addColumn("Precio");
        
        TablaCompetencia.addColumn("Nombre");
        TablaCompetencia.addColumn("Empresa");
        TablaCompetencia.addColumn("Descripcion");
        TablaCompetencia.addColumn("Precio");
        TablaCompetencia.addColumn("Diferencia");
        
        mC = null;
        mBD = null;
        mProducto = null;
        mCP_1 = null;
        
        ClaveProducto = "";
        Seleccion = 0;
        PrecioProducto = 0;
        PreciosCompetencia = null;
        
        mDF = new DecimalFormat("#.####");
        
        LlenarCombo();
        LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JP_ConsultarCompetencia = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TXT_NombreEmpresa1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_NombreProducto1 = new javax.swing.JTextField();
        TXT_Descripcion1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXT_PrecioUnitario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CB_Producto = new javax.swing.JComboBox<>();
        BTN_Guardar = new javax.swing.JButton();
        JP_AgregarCompetencia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_ProductoEncinales = new javax.swing.JTable();
        TXT_Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_ProductoCompetencia = new javax.swing.JTable();
        LBL_Grafico = new javax.swing.JLabel();
        BTN_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Nombre de la empresa");

        jLabel8.setText("Producto");

        jLabel9.setText("Descripción");

        jLabel10.setText("Precio Unitario");

        jLabel1.setText("Comparado con");

        BTN_Guardar.setText("Guardar");
        BTN_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_ConsultarCompetenciaLayout = new javax.swing.GroupLayout(JP_ConsultarCompetencia);
        JP_ConsultarCompetencia.setLayout(JP_ConsultarCompetenciaLayout);
        JP_ConsultarCompetenciaLayout.setHorizontalGroup(
            JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ConsultarCompetenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1))
                .addGap(46, 46, 46)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXT_NombreEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TXT_NombreProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TXT_Descripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TXT_PrecioUnitario1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(CB_Producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(258, 258, 258))
            .addGroup(JP_ConsultarCompetenciaLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(BTN_Guardar)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        JP_ConsultarCompetenciaLayout.setVerticalGroup(
            JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_ConsultarCompetenciaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_NombreEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXT_NombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TXT_Descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TXT_PrecioUnitario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CB_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(BTN_Guardar)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", JP_ConsultarCompetencia);

        TBL_ProductoEncinales.setModel(TablaProductoEncinales);
        TBL_ProductoEncinales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ProductoEncinalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_ProductoEncinales);

        TXT_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_SearchKeyReleased(evt);
            }
        });

        jLabel2.setText("Anclas Mineras Encinales");

        jLabel3.setText("Empresas Externas");

        TBL_ProductoCompetencia.setModel(TablaCompetencia);
        TBL_ProductoCompetencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ProductoCompetenciaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBL_ProductoCompetencia);

        javax.swing.GroupLayout JP_AgregarCompetenciaLayout = new javax.swing.GroupLayout(JP_AgregarCompetencia);
        JP_AgregarCompetencia.setLayout(JP_AgregarCompetenciaLayout);
        JP_AgregarCompetenciaLayout.setHorizontalGroup(
            JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                        .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2))
                        .addGap(12, 12, 12)
                        .addComponent(LBL_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JP_AgregarCompetenciaLayout.setVerticalGroup(
            JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_AgregarCompetenciaLayout.createSequentialGroup()
                .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBL_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TXT_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Ver Tabla", JP_AgregarCompetencia);

        BTN_Atras.setText("Atrás");
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Atras)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        if ("1".equals(Login.Tipousuario))
        {
            Admin mA = new Admin();
            mA.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            if ("2".equals(Login.Tipousuario))
            {
                Cotizador mCot = new Cotizador();
                mCot.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                if ("3".equals(Login.Tipousuario))
                {
                    Ventas mV = new Ventas();
                    mV.setVisible(true);
                    this.setVisible(false);
                }
                else
                {                   
                }
            }
        }
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
        // TODO add your handling code here:
        GuardarCompetencia();
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void TXT_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_SearchKeyReleased
        // TODO add your handling code here:
        LlenarTablaFiltro();
    }//GEN-LAST:event_TXT_SearchKeyReleased

    private void TBL_ProductoEncinalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ProductoEncinalesMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_ProductoEncinales.rowAtPoint(evt.getPoint());       
        ClaveProducto = TBL_ProductoEncinales.getModel().getValueAt(Seleccion, 0).toString();
        PrecioProducto = Double.parseDouble(TBL_ProductoEncinales.getModel().getValueAt(Seleccion, 3).toString());
        LlenarTablaCompetencia();
        LlenarGrafico();
    }//GEN-LAST:event_TBL_ProductoEncinalesMouseClicked

    private void TBL_ProductoCompetenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ProductoCompetenciaMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_ProductoCompetencia.rowAtPoint(evt.getPoint());
        ComparacionPrecios_1.NombreProducto = TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 0).toString();
        ComparacionPrecios_1.NombreEmpresa = TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 1).toString();
        ComparacionPrecios_1.Descripcion = TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 2).toString();
        ComparacionPrecios_1.PrecioUnitario = Double.parseDouble(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 3).toString());
        ComparacionPrecios_1.ClaveProductoComparado = ClaveProducto;
        
        mC = new Competencia();
        mBD = new BD_1();
        
        mC.setEmpresa(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 1).toString());
        mC.setNombreProducto(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 0).toString());
        mC.setPrecioUnitario(Double.parseDouble(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 3).toString()));
        
        
        ComparacionPrecios_1.IdCompetencia = mBD.Consulta_Id_Competencia(mC);
        
        mCP_1 = new ComparacionPrecios_1();
        mCP_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TBL_ProductoCompetenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void GuardarCompetencia()
    {
        mC = new Competencia();
        mBD = new BD_1();
        
        if ( ("".equals(TXT_NombreEmpresa1.getText())) || ("".equals(TXT_NombreProducto1.getText()))
        || ("".equals(TXT_Descripcion1.getText())) || ("".equals(TXT_PrecioUnitario1.getText())) 
        || ("Ninguno".equals(CB_Producto.getSelectedItem())))
        {                  
            JOptionPane.showMessageDialog(null, "Llena bien los campos");
        }
        else
        {
            String Cadena = (String) CB_Producto.getSelectedItem();
            String[] CadenaPartes = Cadena.split("_");
            String ParteCadena1 = CadenaPartes[0];
            
            Random R = new Random();
            int Aleatorio = R.nextInt(1000);
            mC.setClave(TXT_NombreEmpresa1.getText().substring(0,3) + "-" + Aleatorio + "-" + ParteCadena1);
            mC.setEmpresa(TXT_NombreEmpresa1.getText());
            mC.setNombreProducto(TXT_NombreProducto1.getText());
            mC.setDescripcion(TXT_Descripcion1.getText());
            mC.setPrecioUnitario(Double.parseDouble(TXT_PrecioUnitario1.getText()));
            
            if(mBD.AgregarProductoCompetencia(mC, ParteCadena1))
            {

                mBD.Desconectar();
                JOptionPane.showMessageDialog(null, "Precio añadido");
                TXT_NombreEmpresa1.setText("");
                TXT_NombreProducto1.setText("");
                TXT_Descripcion1.setText("");
                TXT_PrecioUnitario1.setText("");
                CB_Producto.setSelectedIndex(0);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existe una falla en la Base de Datos");
            }          
        }
    }
    public void LlenarCombo() 
    {
        CB_Producto.addItem("Ninguno");
        mBD = new BD_1();
        ArrayList mArrayList = new ArrayList();
        mArrayList = mBD.ConsultaNombresProducto();
        //LDBLPrueba.setText(mArrayList.get(0).toString());
        if (mArrayList != null) 
        {

            for (int i = 0; i < mArrayList.size(); i++) 
            {
                CB_Producto.addItem(mArrayList.get(i).toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "No tiene productos en el sistema");
        }
    }
    
    public void LlenarTablaFiltro()
    {
        LimpiarTabla();
        mBD = new BD_1();
        mProducto = new Producto();
        
        ArrayList mListaProducto = mBD.ConsultaProductosFiltro(TXT_Search.getText());
        String [] datos=null;

        for (Object mListaProducto2 : mListaProducto)
        {
            datos = new String[4];
            mProducto = (Producto) mListaProducto2;

            //datos[0] = String.valueOf(mProducto.getIdProducto());
            datos[0] = mProducto.getClave();
            datos[1] = mProducto.getNombreProducto();
            datos[2] = mProducto.getDescripcion();
            datos[3] = String.valueOf(mProducto.getPrecioUnitaro());
            TablaProductoEncinales.addRow(datos);
        }
        this.TBL_ProductoEncinales = new javax.swing.JTable();
        this.TBL_ProductoEncinales.setModel(TablaProductoEncinales);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(2).setPreferredWidth(50);
        if (this.TBL_ProductoEncinales.getRowCount() > 0) 
        {
            this.TBL_ProductoEncinales.setRowSelectionInterval(0, 0);
        }
    }   
    public void LimpiarTabla()
    {
        TablaProductoEncinales = (DefaultTableModel) TBL_ProductoEncinales.getModel();
        int a = TablaProductoEncinales.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaProductoEncinales.removeRow(TablaProductoEncinales.getRowCount() - 1);
        }
    }
    public void LlenarTabla()
    {
        mBD = new BD_1();
        mProducto = new Producto();
        
        ArrayList mListaProducto = mBD.ConsultaProductos();
        String [] datos=null;

        for (Object mListaProducto2 : mListaProducto)
        {
            datos = new String[4];
            mProducto = (Producto) mListaProducto2;

            datos[0] = mProducto.getClave();
            datos[1] = mProducto.getNombreProducto();
            datos[2] = mProducto.getDescripcion();
            datos[3] = String.valueOf(mProducto.getPrecioUnitaro());
            TablaProductoEncinales.addRow(datos);
        }
        this.TBL_ProductoEncinales = new javax.swing.JTable();
        this.TBL_ProductoEncinales.setModel(TablaProductoEncinales);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(2).setPreferredWidth(50);
        if (this.TBL_ProductoEncinales.getRowCount() > 0) 
        {
            this.TBL_ProductoEncinales.setRowSelectionInterval(0, 0);
        }
    }
    
    public void LlenarTablaCompetencia()
    {
        PreciosCompetencia = new ArrayList();
        LimpiarTablaCompetencia();
        mBD = new BD_1();
        mC = new Competencia();
        
        ArrayList mListaProducto = mBD.ConsultaCompetencia(ClaveProducto);
        String [] datos = null;

        for (Object mListaProducto2 : mListaProducto)
        {
            datos = new String[5];
            mC = (Competencia) mListaProducto2;

            datos[0] = mC.getNombreProducto();
            datos[1] = mC.getEmpresa();
            datos[2] = mC.getDescripcion();
            datos[3] = String.valueOf(mC.getPrecioUnitario());
            datos[4] = String.valueOf(mDF.format(Double.parseDouble(datos[3]) - PrecioProducto));
            
            PreciosCompetencia.add(Double.parseDouble(datos[3]));
            TablaCompetencia.addRow(datos);
        }
        this.TBL_ProductoCompetencia = new javax.swing.JTable();
        this.TBL_ProductoCompetencia.setModel(TablaCompetencia);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(2).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(3).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(4).setPreferredWidth(50);
        if (this.TBL_ProductoCompetencia.getRowCount() > 0) 
        {
            this.TBL_ProductoCompetencia.setRowSelectionInterval(0, 0);
        }
    }
    public void LimpiarTablaCompetencia()
    {
        TablaCompetencia = (DefaultTableModel) TBL_ProductoCompetencia.getModel();
        int a = TablaCompetencia.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaCompetencia.removeRow(TablaCompetencia.getRowCount() - 1);
        }
    }
    
    public void LlenarGrafico()
    {   
        DefaultCategoryDataset mDPDS = new DefaultCategoryDataset();
        
        mDPDS.setValue(PrecioProducto, "Precio", "Costo Encinales");
        
        for (int i = 0; i < PreciosCompetencia.size(); i++)
        {
            mDPDS.setValue(Double.parseDouble(PreciosCompetencia.get(i).toString()), "Precio" , ""+(i+1)); 
        }
        
        JFreeChart jFC = ChartFactory.createBarChart3D("Estadística de Precios", "Empresas", "Precios", mDPDS, PlotOrientation.VERTICAL, true, true, false);
        ;
        try 
        {
            OutputStream png = new FileOutputStream("GraficoComparacion.png");
            ChartUtilities.writeBufferedImageAsPNG(png, jFC.createBufferedImage(400, 400));
            png.close();
        } 
        catch (IOException e) 
        {

        }
        String urlImagen = "GraficoComparacion.png";
        ImageIcon img = new ImageIcon(urlImagen);
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(LBL_Grafico.getWidth(), LBL_Grafico.getHeight(), Image.SCALE_DEFAULT));
        LBL_Grafico.setIcon(icon);
        this.repaint();
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComparacionPrecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JComboBox<String> CB_Producto;
    private javax.swing.JPanel JP_AgregarCompetencia;
    private javax.swing.JPanel JP_ConsultarCompetencia;
    private javax.swing.JLabel LBL_Grafico;
    private javax.swing.JTable TBL_ProductoCompetencia;
    private javax.swing.JTable TBL_ProductoEncinales;
    private javax.swing.JTextField TXT_Descripcion1;
    private javax.swing.JTextField TXT_NombreEmpresa1;
    private javax.swing.JTextField TXT_NombreProducto1;
    private javax.swing.JTextField TXT_PrecioUnitario1;
    private javax.swing.JTextField TXT_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
