/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Comparacion;

import BaseDeDatos.*;
import Clases.*;
import Formularios.*;
import java.awt.Event;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author eduardogarciadelgado
 */
public class ComparacionPrecios extends javax.swing.JFrame {

    /**
     * Creates new form ComparacionPrecios
     */
    Competencia mC;
    BD_1 mBD;
    Producto mProducto;
    ComparacionPrecios_1 mCP_1;

    DefaultTableModel TablaProductoEncinales;
    DefaultTableModel TablaCompetencia;

    String ClaveProducto;
    int Seleccion;
    double PrecioProducto;
    ArrayList PreciosCompetencia;

    DecimalFormat mDF;

    public ComparacionPrecios() {

        TablaProductoEncinales = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TablaCompetencia = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cotizador Encinales");
        TablaProductoEncinales.addColumn("Clave");
        TablaProductoEncinales.addColumn("Nombre");
        TablaProductoEncinales.addColumn("Descripción");
        TablaProductoEncinales.addColumn("Precio");

        TablaCompetencia.addColumn("Nombre");
        TablaCompetencia.addColumn("Empresa");
        TablaCompetencia.addColumn("Descripcion");
        TablaCompetencia.addColumn("Precio");
        TablaCompetencia.addColumn("Diferencia");

        mC = null;
        mBD = null;
        mProducto = null;
        mCP_1 = null;

        ClaveProducto = "";
        Seleccion = 0;
        PrecioProducto = 0;
        PreciosCompetencia = null;

        mDF = new DecimalFormat("#.####");

        evitarPegar(TXT_Search);        
        LlenarCombo();
        LlenarTabla();
        
        jLabel14.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jLabel17.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JP_AgregarCompetencia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_ProductoEncinales = new javax.swing.JTable();
        TXT_Search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_ProductoCompetencia = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LBL_Grafico = new javax.swing.JLabel();
        JP_ConsultarCompetencia = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TXT_NombreEmpresa1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_NombreProducto1 = new javax.swing.JTextField();
        TXT_Descripcion1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXT_PrecioUnitario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CB_Producto = new javax.swing.JComboBox<>();
        BTN_Guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BTN_Atras = new javax.swing.JButton();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Sukhumvit Set", 0, 16)); // NOI18N

        JP_AgregarCompetencia.setBackground(new java.awt.Color(255, 255, 255));

        TBL_ProductoEncinales.setModel(TablaProductoEncinales);
        TBL_ProductoEncinales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ProductoEncinalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_ProductoEncinales);

        TXT_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_SearchKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_SearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel2.setText("Anclas Mineras Encinales");

        jLabel3.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel3.setText("Empresas Externas");

        TBL_ProductoCompetencia.setModel(TablaCompetencia);
        TBL_ProductoCompetencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ProductoCompetenciaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBL_ProductoCompetencia);

        jLabel5.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lupa.png"))); // NOI18N
        jLabel5.setText("Buscar Producto");

        jLabel6.setFont(new java.awt.Font("Sukhumvit Set", 0, 22)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/metrica.png"))); // NOI18N
        jLabel6.setText("Tabla Comparativa de Precios");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout JP_AgregarCompetenciaLayout = new javax.swing.GroupLayout(JP_AgregarCompetencia);
        JP_AgregarCompetencia.setLayout(JP_AgregarCompetenciaLayout);
        JP_AgregarCompetenciaLayout.setHorizontalGroup(
            JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_AgregarCompetenciaLayout.createSequentialGroup()
                .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_AgregarCompetenciaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                                .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBL_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(TXT_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_AgregarCompetenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(133, 133, 133))
        );
        JP_AgregarCompetenciaLayout.setVerticalGroup(
            JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(JP_AgregarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_AgregarCompetenciaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_AgregarCompetenciaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(LBL_Grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        jTabbedPane1.addTab("Ver Tabla Comparativa", JP_AgregarCompetencia);

        JP_ConsultarCompetencia.setBackground(new java.awt.Color(255, 255, 255));
        JP_ConsultarCompetencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel7.setText("Nombre de la empresa");
        JP_ConsultarCompetencia.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 391, -1, -1));

        TXT_NombreEmpresa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_NombreEmpresa1KeyTyped(evt);
            }
        });
        JP_ConsultarCompetencia.add(TXT_NombreEmpresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 385, 200, 35));

        jLabel8.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel8.setText("Producto");
        JP_ConsultarCompetencia.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 156, -1, -1));

        TXT_NombreProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NombreProducto1ActionPerformed(evt);
            }
        });
        TXT_NombreProducto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_NombreProducto1KeyTyped(evt);
            }
        });
        JP_ConsultarCompetencia.add(TXT_NombreProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 154, 200, 35));

        TXT_Descripcion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_Descripcion1KeyTyped(evt);
            }
        });
        JP_ConsultarCompetencia.add(TXT_Descripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 229, 200, 35));

        jLabel9.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel9.setText("Descripción");
        JP_ConsultarCompetencia.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 231, -1, -1));

        jLabel10.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel10.setText("Precio Unitario");
        JP_ConsultarCompetencia.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 306, -1, -1));

        TXT_PrecioUnitario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_PrecioUnitario1KeyTyped(evt);
            }
        });
        JP_ConsultarCompetencia.add(TXT_PrecioUnitario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 304, 200, 35));

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel1.setText("Comparado con");
        JP_ConsultarCompetencia.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 461, -1, -1));

        JP_ConsultarCompetencia.add(CB_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 460, 200, 35));

        BTN_Guardar.setFont(new java.awt.Font("Sukhumvit Set", 0, 16)); // NOI18N
        BTN_Guardar.setText("Guardar Producto");
        BTN_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GuardarActionPerformed(evt);
            }
        });
        JP_ConsultarCompetencia.add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 525, 231, 47));

        jLabel4.setFont(new java.awt.Font("Sukhumvit Set", 0, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/portapapeles.png"))); // NOI18N
        jLabel4.setText("Agregar Producto Nuevo a Comparar ");
        JP_ConsultarCompetencia.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("jLabel14");
        JP_ConsultarCompetencia.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 195, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("jLabel15");
        JP_ConsultarCompetencia.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("jLabel16");
        JP_ConsultarCompetencia.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 351, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("jLabel17");
        JP_ConsultarCompetencia.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 426, -1, -1));

        jTabbedPane1.addTab("Agregar Producto Competencia", JP_ConsultarCompetencia);

        jLabel18.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/diagrama (2)_1.png"))); // NOI18N
        jLabel18.setText("  Comparación de Precios ");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel18.setInheritsPopupMenu(false);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/003.jpg"))); // NOI18N

        BTN_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (3).png"))); // NOI18N
        BTN_Atras.setBorderPainted(false);
        BTN_Atras.setContentAreaFilled(false);
        BTN_Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_Atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(144, 144, 144)
                        .addComponent(jLabel11))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(BTN_Atras)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        if ("1".equals(Login.Tipousuario)) {
            Admin mA = new Admin();
            mA.setVisible(true);
            this.setVisible(false);
        } else {
            if ("2".equals(Login.Tipousuario)) {
                Cotizador mCot = new Cotizador();
                mCot.setVisible(true);
                this.setVisible(false);
            } else {
                if ("3".equals(Login.Tipousuario)) {
                    Ventas mV = new Ventas();
                    mV.setVisible(true);
                    this.setVisible(false);
                } else {
                }
            }
        }
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
        // TODO add your handling code here:
        GuardarCompetencia();
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void TXT_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_SearchKeyReleased
        // TODO add your handling code here:
        LlenarTablaFiltro();
    }//GEN-LAST:event_TXT_SearchKeyReleased

    private void TBL_ProductoEncinalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ProductoEncinalesMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_ProductoEncinales.rowAtPoint(evt.getPoint());
        ClaveProducto = TBL_ProductoEncinales.getModel().getValueAt(Seleccion, 0).toString();
        PrecioProducto = Double.parseDouble(TBL_ProductoEncinales.getModel().getValueAt(Seleccion, 3).toString());
        LlenarTablaCompetencia();
        LlenarGrafico();
    }//GEN-LAST:event_TBL_ProductoEncinalesMouseClicked

    private void TBL_ProductoCompetenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ProductoCompetenciaMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_ProductoCompetencia.rowAtPoint(evt.getPoint());
        ComparacionPrecios_1.NombreProducto = TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 0).toString();
        ComparacionPrecios_1.NombreEmpresa = TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 1).toString();
        ComparacionPrecios_1.Descripcion = TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 2).toString();
        ComparacionPrecios_1.PrecioUnitario = Double.parseDouble(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 3).toString());
        ComparacionPrecios_1.ClaveProductoComparado = ClaveProducto;

        mC = new Competencia();
        mBD = new BD_1();

        mC.setEmpresa(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 1).toString());
        mC.setNombreProducto(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 0).toString());
        mC.setPrecioUnitario(Double.parseDouble(TBL_ProductoCompetencia.getModel().getValueAt(Seleccion, 3).toString()));

        ComparacionPrecios_1.IdCompetencia = mBD.Consulta_Id_Competencia(mC);

        mCP_1 = new ComparacionPrecios_1();
        mCP_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TBL_ProductoCompetenciaMouseClicked

    private void TXT_NombreProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NombreProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NombreProducto1ActionPerformed

    private void TXT_SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_SearchKeyTyped
        // TODO add your handling code here:
        if ((this.TXT_Search.getText().length() == 45)) {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_SearchKeyTyped

    private void TXT_NombreProducto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_NombreProducto1KeyTyped
        // TODO add your handling code here:
        if (this.TXT_NombreProducto1.getText().isEmpty()) {
            this.jLabel14.setText("");
        } else if ((this.TXT_NombreProducto1.getText().length() == 45)) {
            evt.consume();

        } else if (this.TXT_NombreProducto1.getText().length() < 4) {
            this.jLabel14.setText("Nombre Demasiado Corta");
        } else if (this.TXT_NombreProducto1.getText().length() > 4) {
            this.jLabel14.setText("");
        }
    }//GEN-LAST:event_TXT_NombreProducto1KeyTyped

    private void TXT_Descripcion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_Descripcion1KeyTyped
        // TODO add your handling code here:
        if (this.TXT_Descripcion1.getText().isEmpty()) {
            this.jLabel15.setText("");
        } else if ((this.TXT_Descripcion1.getText().length() == 45)) {
            evt.consume();

        } else if (this.TXT_Descripcion1.getText().length() < 8) {
            this.jLabel15.setText("Descripción Demasiado Corta");
        } else if (this.TXT_Descripcion1.getText().length() > 8) {
            this.jLabel15.setText("");
        }
    }//GEN-LAST:event_TXT_Descripcion1KeyTyped

    private void TXT_PrecioUnitario1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_PrecioUnitario1KeyTyped
        // TODO add your handling code here:
       
            char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }
        
        if (this.TXT_PrecioUnitario1.getText().isEmpty()) {
            this.jLabel6.setText("");
        } else if (this.TXT_PrecioUnitario1.getText().length() == 10) {
            evt.consume();
        } else if (this.TXT_PrecioUnitario1.getText().length() < 2) {
            this.jLabel6.setText("Precio Invalido");
        } else if (this.TXT_PrecioUnitario1.getText().length() >= 2) {
            this.jLabel6.setText("");
        }

        if (evt.getKeyChar() == '.' && TXT_PrecioUnitario1.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_PrecioUnitario1KeyTyped

    private void TXT_NombreEmpresa1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_NombreEmpresa1KeyTyped
        // TODO add your handling code here:
        if (this.TXT_NombreEmpresa1.getText().isEmpty()) {
            this.jLabel17.setText("");
        } else if ((this.TXT_NombreEmpresa1.getText().length() == 45)) {
            evt.consume();

        } else if (this.TXT_NombreEmpresa1.getText().length() < 8) {
            this.jLabel17.setText("Descripsion Demasiado Corta");
        } else if (this.TXT_NombreEmpresa1.getText().length() > 8) {
            this.jLabel17.setText("");
        }
    }//GEN-LAST:event_TXT_NombreEmpresa1KeyTyped

    public static void evitarPegar(JTextField campo) {

        InputMap map2 = campo.getInputMap(JTextField.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

    }

    /**
     * @param args the command line arguments
     */
    public void GuardarCompetencia() {
        mC = new Competencia();
        mBD = new BD_1();

        if (("".equals(TXT_NombreEmpresa1.getText())) || ("".equals(TXT_NombreProducto1.getText()))
                || ("".equals(TXT_Descripcion1.getText())) || ("".equals(TXT_PrecioUnitario1.getText()))
                || ("Ninguno".equals(CB_Producto.getSelectedItem()))) {
            JOptionPane.showMessageDialog(null, "Llena bien los campos");
        } else {
            String Cadena = (String) CB_Producto.getSelectedItem();
            String[] CadenaPartes = Cadena.split("_");
            String ParteCadena1 = CadenaPartes[0];

            Random R = new Random();
            int Aleatorio = R.nextInt(1000);
            mC.setClave(TXT_NombreEmpresa1.getText().substring(0, 3) + "-" + Aleatorio + "-" + ParteCadena1);
            mC.setEmpresa(TXT_NombreEmpresa1.getText());
            mC.setNombreProducto(TXT_NombreProducto1.getText());
            mC.setDescripcion(TXT_Descripcion1.getText());
            mC.setPrecioUnitario(Double.parseDouble(TXT_PrecioUnitario1.getText()));

            if (mBD.AgregarProductoCompetencia(mC, ParteCadena1)) {

                mBD.Desconectar();
                JOptionPane.showMessageDialog(null, "Precio añadido");
                TXT_NombreEmpresa1.setText("");
                TXT_NombreProducto1.setText("");
                TXT_Descripcion1.setText("");
                TXT_PrecioUnitario1.setText("");
                CB_Producto.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "Existe una falla en la Base de Datos");
            }
        }
    }

    public void LlenarCombo() {
        CB_Producto.addItem("Ninguno");
        mBD = new BD_1();
        ArrayList mArrayList = new ArrayList();
        mArrayList = mBD.ConsultaNombresProducto();
        //LDBLPrueba.setText(mArrayList.get(0).toString());
        if (mArrayList != null) {

            for (int i = 0; i < mArrayList.size(); i++) {
                CB_Producto.addItem(mArrayList.get(i).toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "No tiene productos en el sistema");
        }
    }

    public void LlenarTablaFiltro() {
        LimpiarTabla();
        mBD = new BD_1();
        mProducto = new Producto();

        ArrayList mListaProducto = mBD.ConsultaProductosFiltro(TXT_Search.getText());
        String[] datos = null;

        for (Object mListaProducto2 : mListaProducto) {
            datos = new String[4];
            mProducto = (Producto) mListaProducto2;

            //datos[0] = String.valueOf(mProducto.getIdProducto());
            datos[0] = mProducto.getClave();
            datos[1] = mProducto.getNombreProducto();
            datos[2] = mProducto.getDescripcion();
            datos[3] = String.valueOf(mProducto.getPrecioUnitaro());
            TablaProductoEncinales.addRow(datos);
        }
        this.TBL_ProductoEncinales = new javax.swing.JTable();
        this.TBL_ProductoEncinales.setModel(TablaProductoEncinales);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(2).setPreferredWidth(50);
        if (this.TBL_ProductoEncinales.getRowCount() > 0) {
            this.TBL_ProductoEncinales.setRowSelectionInterval(0, 0);
        }
    }

    public void LimpiarTabla() {
        TablaProductoEncinales = (DefaultTableModel) TBL_ProductoEncinales.getModel();
        int a = TablaProductoEncinales.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaProductoEncinales.removeRow(TablaProductoEncinales.getRowCount() - 1);
        }
    }

    public void LlenarTabla() {
        mBD = new BD_1();
        mProducto = new Producto();

        ArrayList mListaProducto = mBD.ConsultaProductos();
        String[] datos = null;

        for (Object mListaProducto2 : mListaProducto) {
            datos = new String[4];
            mProducto = (Producto) mListaProducto2;

            datos[0] = mProducto.getClave();
            datos[1] = mProducto.getNombreProducto();
            datos[2] = mProducto.getDescripcion();
            datos[3] = String.valueOf(mProducto.getPrecioUnitaro());
            TablaProductoEncinales.addRow(datos);
        }
        this.TBL_ProductoEncinales = new javax.swing.JTable();
        this.TBL_ProductoEncinales.setModel(TablaProductoEncinales);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ProductoEncinales.getColumnModel().getColumn(2).setPreferredWidth(50);
        if (this.TBL_ProductoEncinales.getRowCount() > 0) {
            this.TBL_ProductoEncinales.setRowSelectionInterval(0, 0);
        }
    }

    public void LlenarTablaCompetencia() {
        PreciosCompetencia = new ArrayList();
        LimpiarTablaCompetencia();
        mBD = new BD_1();
        mC = new Competencia();

        ArrayList mListaProducto = mBD.ConsultaCompetencia(ClaveProducto);
        String[] datos = null;

        for (Object mListaProducto2 : mListaProducto) {
            datos = new String[5];
            mC = (Competencia) mListaProducto2;

            datos[0] = mC.getNombreProducto();
            datos[1] = mC.getEmpresa();
            datos[2] = mC.getDescripcion();
            datos[3] = String.valueOf(mC.getPrecioUnitario());
            datos[4] = String.valueOf(mDF.format(Double.parseDouble(datos[3]) - PrecioProducto));

            PreciosCompetencia.add(Double.parseDouble(datos[3]));
            TablaCompetencia.addRow(datos);
        }
        this.TBL_ProductoCompetencia = new javax.swing.JTable();
        this.TBL_ProductoCompetencia.setModel(TablaCompetencia);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(2).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(3).setPreferredWidth(50);
        this.TBL_ProductoCompetencia.getColumnModel().getColumn(4).setPreferredWidth(50);
        if (this.TBL_ProductoCompetencia.getRowCount() > 0) {
            this.TBL_ProductoCompetencia.setRowSelectionInterval(0, 0);
        }
    }

    public void LimpiarTablaCompetencia() {
        TablaCompetencia = (DefaultTableModel) TBL_ProductoCompetencia.getModel();
        int a = TablaCompetencia.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaCompetencia.removeRow(TablaCompetencia.getRowCount() - 1);
        }
    }

    public void LlenarGrafico() {
        DefaultCategoryDataset mDPDS = new DefaultCategoryDataset();

        mDPDS.setValue(PrecioProducto, "Precio", "Costo Encinales");

        for (int i = 0; i < PreciosCompetencia.size(); i++) {
            mDPDS.setValue(Double.parseDouble(PreciosCompetencia.get(i).toString()), "Precio", "" + (i + 1));
        }

        JFreeChart jFC = ChartFactory.createBarChart3D("Estadística de Precios", "Empresas", "Precios", mDPDS, PlotOrientation.VERTICAL, true, true, false);
        
        try {
            OutputStream png = new FileOutputStream("GraficoComparacion.png");
            ChartUtilities.writeBufferedImageAsPNG(png, jFC.createBufferedImage(400, 400));
            png.close();
        } catch (IOException e) {

        }
        String urlImagen = "GraficoComparacion.png";
        ImageIcon img = new ImageIcon(urlImagen);
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(LBL_Grafico.getWidth(), LBL_Grafico.getHeight(), Image.SCALE_DEFAULT));
        LBL_Grafico.setIcon(icon);
        this.repaint();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComparacionPrecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JComboBox<String> CB_Producto;
    private javax.swing.JPanel JP_AgregarCompetencia;
    private javax.swing.JPanel JP_ConsultarCompetencia;
    private javax.swing.JLabel LBL_Grafico;
    private javax.swing.JTable TBL_ProductoCompetencia;
    private javax.swing.JTable TBL_ProductoEncinales;
    private javax.swing.JTextField TXT_Descripcion1;
    private javax.swing.JTextField TXT_NombreEmpresa1;
    private javax.swing.JTextField TXT_NombreProducto1;
    private javax.swing.JTextField TXT_PrecioUnitario1;
    private javax.swing.JTextField TXT_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
