/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Comparacion;

import BaseDeDatos.*;
import Clases.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardogarciadelgado
 */
public class ComparacionPrecios_1 extends javax.swing.JFrame {

    /**
     * Creates new form ComparacionPrecios_1
     */
    
    public static String NombreEmpresa;
    public static String NombreProducto;
    public static String Descripcion;
    public static double PrecioUnitario;
    public static String ClaveProductoComparado;
    public static int IdCompetencia;
    int Opcion;
    
    BD_1 mBD;
    ComparacionPrecios mCP;
    Competencia mC;
    
    public ComparacionPrecios_1() {
        initComponents();
        
        mBD = null;
        mCP = null;
        mC = null;
        
        LlenarCombo();
        
        TXT_NombreEmpresa1.setText(NombreEmpresa);
        TXT_NombreProducto1.setText(NombreProducto);
        TXT_Descripcion1.setText(Descripcion);
        TXT_PrecioUnitario1.setText(String.valueOf(PrecioUnitario));        
        for (int i = 0; i <= CB_Producto.getItemListeners().length; i++)
        {           
            if (CB_Producto.getItemAt(i).substring(0,6).equals(ClaveProductoComparado))
            {
                CB_Producto.setSelectedIndex(i);
            }
        }
        
        Opcion = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_ConsultarCompetencia = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TXT_NombreEmpresa1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_NombreProducto1 = new javax.swing.JTextField();
        TXT_Descripcion1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXT_PrecioUnitario1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CB_Producto = new javax.swing.JComboBox<>();
        BTN_Modificar = new javax.swing.JButton();
        BTN_Eliminar = new javax.swing.JButton();
        BTN_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Nombre de la empresa");

        jLabel8.setText("Producto");

        jLabel9.setText("Descripción");

        jLabel10.setText("Precio Unitario");

        jLabel1.setText("Comparado con");

        BTN_Modificar.setText("Modificar");
        BTN_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ModificarActionPerformed(evt);
            }
        });

        BTN_Eliminar.setText("Eliminar");
        BTN_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EliminarActionPerformed(evt);
            }
        });

        BTN_Atras.setText("Atrás");
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_ConsultarCompetenciaLayout = new javax.swing.GroupLayout(JP_ConsultarCompetencia);
        JP_ConsultarCompetencia.setLayout(JP_ConsultarCompetenciaLayout);
        JP_ConsultarCompetenciaLayout.setHorizontalGroup(
            JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ConsultarCompetenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JP_ConsultarCompetenciaLayout.createSequentialGroup()
                        .addComponent(BTN_Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Eliminar))
                    .addGroup(JP_ConsultarCompetenciaLayout.createSequentialGroup()
                        .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46)
                        .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXT_NombreEmpresa1)
                            .addComponent(TXT_NombreProducto1)
                            .addComponent(TXT_Descripcion1)
                            .addComponent(TXT_PrecioUnitario1)
                            .addComponent(CB_Producto, 0, 200, Short.MAX_VALUE))))
                .addGap(258, 258, 258))
            .addGroup(JP_ConsultarCompetenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Atras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_ConsultarCompetenciaLayout.setVerticalGroup(
            JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_ConsultarCompetenciaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(BTN_Atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_NombreEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXT_NombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TXT_Descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TXT_PrecioUnitario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CB_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(JP_ConsultarCompetenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Modificar)
                    .addComponent(BTN_Eliminar))
                .addContainerGap(426, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP_ConsultarCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP_ConsultarCompetencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
        // TODO add your handling code here:
        ActualizarCompetencia();
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EliminarActionPerformed
        // TODO add your handling code here:
        Opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este precio? \n (los precios eliminados no se pueden recuperar)");
        
        if (JOptionPane.OK_OPTION == Opcion)
        {
            EliminarCompetencia();
        }
        else
        {
            
        }
    }//GEN-LAST:event_BTN_EliminarActionPerformed

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        mCP = new ComparacionPrecios();
        mCP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    public void LlenarCombo() 
    {
        CB_Producto.addItem("Ninguno");
        mBD = new BD_1();
        ArrayList mArrayList = new ArrayList();
        mArrayList = mBD.ConsultaNombresProducto();
        //LDBLPrueba.setText(mArrayList.get(0).toString());
        if (mArrayList != null) 
        {

            for (int i = 0; i < mArrayList.size(); i++) 
            {
                CB_Producto.addItem(mArrayList.get(i).toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "No tiene productos en el sistema");
        }
    }
    
    public void ActualizarCompetencia()
    {
        mC = new Competencia();
        mBD = new BD_1();
        
        if ( ("".equals(TXT_NombreEmpresa1.getText())) || ("".equals(TXT_NombreProducto1.getText()))
        || ("".equals(TXT_Descripcion1.getText())) || ("".equals(TXT_PrecioUnitario1.getText())) 
        || ("Ninguno".equals(CB_Producto.getSelectedItem())))
        {                  
            JOptionPane.showMessageDialog(null, "Llena bien los campos");
        }
        else
        {
            String Cadena = (String) CB_Producto.getSelectedItem();
            String[] CadenaPartes = Cadena.split("_");
            
            mC.setEmpresa(TXT_NombreEmpresa1.getText());
            mC.setNombreProducto(TXT_NombreProducto1.getText());
            mC.setDescripcion(TXT_Descripcion1.getText());
            mC.setPrecioUnitario(Double.parseDouble(TXT_PrecioUnitario1.getText()));
            mC.setProducto_idProducto(mBD.ConsultarIdProductoClave(CadenaPartes[0]));
            
            if(mBD.ModificarProductoCompetencia(mC, IdCompetencia))
            {

                mBD.Desconectar();
                JOptionPane.showMessageDialog(null, "Producto Modificado");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existe una falla en la Base de Datos");
            }
        }
    }
    
    public void EliminarCompetencia()
    {
        mBD = new BD_1();
        if (mBD.EliminarCompetencia(IdCompetencia))
        {
            JOptionPane.showMessageDialog(null, "Producto Eliminado");
            mCP = new ComparacionPrecios();
            mCP.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComparacionPrecios_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComparacionPrecios_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_Eliminar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JComboBox<String> CB_Producto;
    private javax.swing.JPanel JP_ConsultarCompetencia;
    private javax.swing.JTextField TXT_Descripcion1;
    private javax.swing.JTextField TXT_NombreEmpresa1;
    private javax.swing.JTextField TXT_NombreProducto1;
    private javax.swing.JTextField TXT_PrecioUnitario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
