/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Cotizacion;

import BaseDeDatos.*;
import Clases.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardogarciadelgado
 */
public class ConsumoElectrico extends javax.swing.JFrame {

    /**
     * Creates new form ConsumoElectrico
     */
    
    MenuCotizacion mMC;
    BD_1 mBD;
    PreciosProduccion mPP;
    Constantes mC;
    ClaseConsumoElectrico mCCE;
    ConsumoElectrico_1 mCE_1;
    DP_ConsumoElectrico mDP_CE;
    ReporteCostos mRC;
    
    DefaultTableModel TablaProducto;
    DefaultTableModel TablaConsumoElectrico;    
    DefaultTableModel TablaCostosTotalesCE;
    
    DecimalFormat mDF;
    
    int Seleccion;
    
    public ConsumoElectrico() {
        this.TablaProducto = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return (row == 0) && (column==2);
            }
        };
        this.TablaConsumoElectrico = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        this.TablaCostosTotalesCE = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cotizador Encinales");
        mC = null;
        mBD = null;
        mPP = null;
        mC = null;
        mCE_1 = null;
        mCCE = null;
        mDP_CE = null;
        mRC = null;
                
        TablaProducto.addColumn("Clave");
        TablaProducto.addColumn("Nombre");
        
        TablaConsumoElectrico.addColumn("ID");
        TablaConsumoElectrico.addColumn("Nombre");
        TablaConsumoElectrico.addColumn("KW por Equipo");
        TablaConsumoElectrico.addColumn("Número de equipos");
        TablaConsumoElectrico.addColumn("Horas de consumo");
        TablaConsumoElectrico.addColumn("KW por hora");
        TablaConsumoElectrico.addColumn("Watts por día");
        TablaConsumoElectrico.addColumn("KW por día");
        TablaConsumoElectrico.addColumn("Días del mes");
        TablaConsumoElectrico.addColumn("KW por Mes");
        
        TablaCostosTotalesCE.addColumn("Costo por unidad");
        TablaCostosTotalesCE.addColumn("Costo");
        
        mDF = new DecimalFormat("#.#####");
        
        Seleccion = 0;
        
        LlenarTablaProducto();
        LlenarTablaConsumosElectrico();
        LlenarTablaCostoProduccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTN_Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_MostrarProducto = new javax.swing.JTable();
        BTN_PreciosProduccion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_ConsumoElectrico = new javax.swing.JTable();
        BTN_AgregarCostoProduccion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBL_TotalesCE = new javax.swing.JTable();
        BTN_Reporte = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BTN_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (3).png"))); // NOI18N
        BTN_Atras.setBorderPainted(false);
        BTN_Atras.setContentAreaFilled(false);
        BTN_Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 22)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/energia-renovable.png"))); // NOI18N
        jLabel1.setText("  Determinación Costos De Consumo Eléctrico");

        TBL_MostrarProducto.setModel(TablaProducto);
        jScrollPane1.setViewportView(TBL_MostrarProducto);

        BTN_PreciosProduccion.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_PreciosProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/factory_1.png"))); // NOI18N
        BTN_PreciosProduccion.setText("Ir a Precios de Producción");
        BTN_PreciosProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_PreciosProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PreciosProduccionActionPerformed(evt);
            }
        });

        TBL_ConsumoElectrico.setModel(TablaConsumoElectrico);
        TBL_ConsumoElectrico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ConsumoElectricoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBL_ConsumoElectrico);

        BTN_AgregarCostoProduccion.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_AgregarCostoProduccion.setText("Añadir Equipo Eléctrico");
        BTN_AgregarCostoProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AgregarCostoProduccionActionPerformed(evt);
            }
        });

        TBL_TotalesCE.setModel(TablaCostosTotalesCE);
        jScrollPane3.setViewportView(TBL_TotalesCE);

        BTN_Reporte.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/estadistica.png"))); // NOI18N
        BTN_Reporte.setText("Ir a Reporte de Costos");
        BTN_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ReporteActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/003.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_AgregarCostoProduccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_PreciosProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BTN_Atras)
                    .addContainerGap(831, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(BTN_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BTN_PreciosProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_AgregarCostoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BTN_Atras)
                    .addContainerGap(625, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        mMC = new MenuCotizacion();
        mMC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void BTN_PreciosProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PreciosProduccionActionPerformed
        // TODO add your handling code here:
        mPP = new PreciosProduccion();
        mPP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_PreciosProduccionActionPerformed

    private void TBL_ConsumoElectricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ConsumoElectricoMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_ConsumoElectrico.rowAtPoint(evt.getPoint());
        ConsumoElectrico_1.idConsumoElectrico = Integer.parseInt(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 0).toString());
        ConsumoElectrico_1.NombreEquipo = TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 1).toString();
        ConsumoElectrico_1.ConsumoKwEq = Double.parseDouble(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 2).toString());
        ConsumoElectrico_1.NumeroEquipos = Integer.parseInt(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 3).toString());
        ConsumoElectrico_1.HorasConsumo = Double.parseDouble(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 4).toString());
        ConsumoElectrico_1.Bandera = true;
        mCE_1 = new ConsumoElectrico_1();
        mCE_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TBL_ConsumoElectricoMouseClicked

    private void BTN_AgregarCostoProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AgregarCostoProduccionActionPerformed
        // TODO add your handling code here:
        ConsumoElectrico_1.Bandera = false;
        mCE_1 = new ConsumoElectrico_1();
        mCE_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AgregarCostoProduccionActionPerformed

    private void BTN_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ReporteActionPerformed
        // TODO add your handling code here:
        mRC = new ReporteCostos();
        mRC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_ReporteActionPerformed

    public void LlenarTablaProducto()
    {
        String[] Datos = new String[2];
        Datos[0] = MenuCotizacion.Clave;
        Datos[1] = MenuCotizacion.NombreProducto;        
        TablaProducto.addRow(Datos);
    }

    public void LlenarTablaConsumosElectrico()
    {
        mBD = new BD_1();
        mCCE = new ClaseConsumoElectrico();
        
        ArrayList mListaConsumosElectricos = mBD.ConsultaConsumosElectricos(MenuCotizacion.Clave);
        String [] datos;
        
        for (Object mListaConsElec : mListaConsumosElectricos)
        {
            datos = new String[10];
            mCCE = (ClaseConsumoElectrico) mListaConsElec;

            datos[0] = String.valueOf(mCCE.getIdConsumoElectrico());
            datos[1] = mCCE.getNombreEquipos();
            datos[2] = String.valueOf(mCCE.getConsumoKW_Eq());
            datos[3] = String.valueOf(mCCE.getNumeroEquipo());
            datos[4] = String.valueOf(mCCE.getHorasEquipo());
            datos[5] = String.valueOf(mCCE.getKW_Hora());
            datos[6] = String.valueOf(mCCE.getWatts_Dia());
            datos[7] = String.valueOf(mCCE.getKW_Dia());
            datos[8] = String.valueOf(mCCE.getDiasPorMes());
            datos[9] = String.valueOf(mDF.format(mCCE.getKW_Mes()));
            TablaConsumoElectrico.addRow(datos);
        }
        this.TBL_ConsumoElectrico = new javax.swing.JTable();
        this.TBL_ConsumoElectrico.setModel(TablaConsumoElectrico);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(0).setPreferredWidth(10);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(2).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(3).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(4).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(5).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(6).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(7).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(8).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(9).setPreferredWidth(50);
        if (this.TBL_ConsumoElectrico.getRowCount() > 0) 
        {
            this.TBL_ConsumoElectrico.setRowSelectionInterval(0, 0);
        }
    }
    
    public void LlenarTablaCostoProduccion()
    {
        mBD = new BD_1();
        mCCE = new ClaseConsumoElectrico();
        mC = new Constantes();
        String [] datos;
        ArrayList mListaConstantes = mBD.ConsultaConstantes();
        
        for (Object mListaConstantes2 : mListaConstantes)
        {
            mC = (Constantes) mListaConstantes2;
        }       
        
        if (TablaConsumoElectrico.getRowCount() != 0)
        {
            mDP_CE = new DP_ConsumoElectrico();           
            datos = new String[2];
            
            datos[0] = "Costo Total KW/Hora";
            mDP_CE.setTotalKwHora(mBD.SumarConsumosElectricos(MenuCotizacion.Clave));
            datos[1] = String.valueOf(mDF.format(mDP_CE.getTotalKwHora()));
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "Precio KW/Mes";
            mDP_CE.setPrecioKwHora(mC.getPrecioKW_Mes());
            datos[1] = String.valueOf(mC.getPrecioKW_Mes());
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "Precio KW/Hora por Mes";
            mDP_CE.setSubtotal(mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes());
            datos[1] = String.valueOf(mDF.format(mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()));
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "IVA";
            datos[1] = String.valueOf(mDF.format(((mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()) * mC.getIVA()) /100));
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "Total";
            mDP_CE.setPrecioConIVA((((mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()) * mC.getIVA()) /100) + (mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()));
            datos[1] = String.valueOf(mDF.format((((mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()) * mC.getIVA()) /100) + (mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes())));
            TablaCostosTotalesCE.addRow(datos);
            
            if(mBD.AgregarCostoConsumoElectrico(mDP_CE, MenuCotizacion.Clave))
            {
                //SE MODIFICA O SE AÑADE EL COSTO DE PRODUCCION
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existe una falla en la Base de Datos");
            }
            
        }
        else
        {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsumoElectrico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AgregarCostoProduccion;
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_PreciosProduccion;
    private javax.swing.JButton BTN_Reporte;
    private javax.swing.JTable TBL_ConsumoElectrico;
    private javax.swing.JTable TBL_MostrarProducto;
    private javax.swing.JTable TBL_TotalesCE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
