/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Cotizacion;

import BaseDeDatos.*;
import Clases.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardogarciadelgado
 */
public class ConsumoElectrico extends javax.swing.JFrame {

    /**
     * Creates new form ConsumoElectrico
     */
    
    MenuCotizacion mMC;
    BD_1 mBD;
    PreciosProduccion mPP;
    Constantes mC;
    ClaseConsumoElectrico mCCE;
    ConsumoElectrico_1 mCE_1;
    DP_ConsumoElectrico mDP_CE;
    ReporteCostos mRC;
    
    DefaultTableModel TablaProducto;
    DefaultTableModel TablaConsumoElectrico;    
    DefaultTableModel TablaCostosTotalesCE;
    
    DecimalFormat mDF;
    
    int Seleccion;
    
    public ConsumoElectrico() {
        this.TablaProducto = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return (row == 0) && (column==2);
            }
        };
        this.TablaConsumoElectrico = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        this.TablaCostosTotalesCE = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        
        initComponents();
        mC = null;
        mBD = null;
        mPP = null;
        mC = null;
        mCE_1 = null;
        mCCE = null;
        mDP_CE = null;
        mRC = null;
                
        TablaProducto.addColumn("Clave");
        TablaProducto.addColumn("Nombre");
        
        TablaConsumoElectrico.addColumn("ID");
        TablaConsumoElectrico.addColumn("Nombre");
        TablaConsumoElectrico.addColumn("KW por Equipo");
        TablaConsumoElectrico.addColumn("Número de equipos");
        TablaConsumoElectrico.addColumn("Horas de consumo");
        TablaConsumoElectrico.addColumn("KW por hora");
        TablaConsumoElectrico.addColumn("Watts por día");
        TablaConsumoElectrico.addColumn("KW por día");
        TablaConsumoElectrico.addColumn("Días del mes");
        TablaConsumoElectrico.addColumn("KW por Mes");
        
        TablaCostosTotalesCE.addColumn("Costo por unidad");
        TablaCostosTotalesCE.addColumn("Costo");
        
        mDF = new DecimalFormat("#.#####");
        
        Seleccion = 0;
        
        LlenarTablaProducto();
        LlenarTablaConsumosElectrico();
        LlenarTablaCostoProduccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_MostrarProducto = new javax.swing.JTable();
        BTN_PreciosProduccion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_ConsumoElectrico = new javax.swing.JTable();
        BTN_AgregarCostoProduccion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBL_TotalesCE = new javax.swing.JTable();
        BTN_Reporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_Atras.setText("Atras");
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("DETERMINACIÓN COSTOS DE CONSUMO ELÉCTRICO");

        TBL_MostrarProducto.setModel(TablaProducto);
        jScrollPane1.setViewportView(TBL_MostrarProducto);

        BTN_PreciosProduccion.setText("Ir a Precios de Produccion");
        BTN_PreciosProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PreciosProduccionActionPerformed(evt);
            }
        });

        TBL_ConsumoElectrico.setModel(TablaConsumoElectrico);
        TBL_ConsumoElectrico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ConsumoElectricoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBL_ConsumoElectrico);

        BTN_AgregarCostoProduccion.setText("Añadir");
        BTN_AgregarCostoProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AgregarCostoProduccionActionPerformed(evt);
            }
        });

        TBL_TotalesCE.setModel(TablaCostosTotalesCE);
        jScrollPane3.setViewportView(TBL_TotalesCE);

        BTN_Reporte.setText("Reporte de Costos");
        BTN_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_AgregarCostoProduccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_Atras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTN_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_PreciosProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Atras)
                    .addComponent(BTN_PreciosProduccion)
                    .addComponent(BTN_Reporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_AgregarCostoProduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        mMC = new MenuCotizacion();
        mMC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void BTN_PreciosProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PreciosProduccionActionPerformed
        // TODO add your handling code here:
        mPP = new PreciosProduccion();
        mPP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_PreciosProduccionActionPerformed

    private void TBL_ConsumoElectricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ConsumoElectricoMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_ConsumoElectrico.rowAtPoint(evt.getPoint());
        ConsumoElectrico_1.idConsumoElectrico = Integer.parseInt(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 0).toString());
        ConsumoElectrico_1.NombreEquipo = TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 1).toString();
        ConsumoElectrico_1.ConsumoKwEq = Double.parseDouble(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 2).toString());
        ConsumoElectrico_1.NumeroEquipos = Integer.parseInt(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 3).toString());
        ConsumoElectrico_1.HorasConsumo = Double.parseDouble(TBL_ConsumoElectrico.getModel().getValueAt(Seleccion, 4).toString());
        ConsumoElectrico_1.Bandera = true;
        mCE_1 = new ConsumoElectrico_1();
        mCE_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TBL_ConsumoElectricoMouseClicked

    private void BTN_AgregarCostoProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AgregarCostoProduccionActionPerformed
        // TODO add your handling code here:
        ConsumoElectrico_1.Bandera = false;
        mCE_1 = new ConsumoElectrico_1();
        mCE_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AgregarCostoProduccionActionPerformed

    private void BTN_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ReporteActionPerformed
        // TODO add your handling code here:
        mRC = new ReporteCostos();
        mRC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_ReporteActionPerformed

    public void LlenarTablaProducto()
    {
        String[] Datos = new String[2];
        Datos[0] = MenuCotizacion.Clave;
        Datos[1] = MenuCotizacion.NombreProducto;        
        TablaProducto.addRow(Datos);
    }

    public void LlenarTablaConsumosElectrico()
    {
        mBD = new BD_1();
        mCCE = new ClaseConsumoElectrico();
        
        ArrayList mListaConsumosElectricos = mBD.ConsultaConsumosElectricos(MenuCotizacion.Clave);
        String [] datos;
        
        for (Object mListaConsElec : mListaConsumosElectricos)
        {
            datos = new String[10];
            mCCE = (ClaseConsumoElectrico) mListaConsElec;

            datos[0] = String.valueOf(mCCE.getIdConsumoElectrico());
            datos[1] = mCCE.getNombreEquipos();
            datos[2] = String.valueOf(mCCE.getConsumoKW_Eq());
            datos[3] = String.valueOf(mCCE.getNumeroEquipo());
            datos[4] = String.valueOf(mCCE.getHorasEquipo());
            datos[5] = String.valueOf(mCCE.getKW_Hora());
            datos[6] = String.valueOf(mCCE.getWatts_Dia());
            datos[7] = String.valueOf(mCCE.getKW_Dia());
            datos[8] = String.valueOf(mCCE.getDiasPorMes());
            datos[9] = String.valueOf(mDF.format(mCCE.getKW_Mes()));
            TablaConsumoElectrico.addRow(datos);
        }
        this.TBL_ConsumoElectrico = new javax.swing.JTable();
        this.TBL_ConsumoElectrico.setModel(TablaConsumoElectrico);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(0).setPreferredWidth(10);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(2).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(3).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(4).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(5).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(6).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(7).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(8).setPreferredWidth(50);
        this.TBL_ConsumoElectrico.getColumnModel().getColumn(9).setPreferredWidth(50);
        if (this.TBL_ConsumoElectrico.getRowCount() > 0) 
        {
            this.TBL_ConsumoElectrico.setRowSelectionInterval(0, 0);
        }
    }
    
    public void LlenarTablaCostoProduccion()
    {
        mBD = new BD_1();
        mCCE = new ClaseConsumoElectrico();
        mC = new Constantes();
        String [] datos;
        ArrayList mListaConstantes = mBD.ConsultaConstantes();
        
        for (Object mListaConstantes2 : mListaConstantes)
        {
            mC = (Constantes) mListaConstantes2;
        }       
        
        if (TablaConsumoElectrico.getRowCount() != 0)
        {
            mDP_CE = new DP_ConsumoElectrico();           
            datos = new String[2];
            
            datos[0] = "Costo Total KW/Hora";
            mDP_CE.setTotalKwHora(mBD.SumarConsumosElectricos(MenuCotizacion.Clave));
            datos[1] = String.valueOf(mDF.format(mDP_CE.getTotalKwHora()));
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "Precio KW/Mes";
            mDP_CE.setPrecioKwHora(mC.getPrecioKW_Mes());
            datos[1] = String.valueOf(mC.getPrecioKW_Mes());
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "Precio KW/Hora por Mes";
            mDP_CE.setSubtotal(mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes());
            datos[1] = String.valueOf(mDF.format(mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()));
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "IVA";
            datos[1] = String.valueOf(mDF.format(((mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()) * mC.getIVA()) /100));
            TablaCostosTotalesCE.addRow(datos);
            
            datos[0] = "Total";
            mDP_CE.setPrecioConIVA((((mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()) * mC.getIVA()) /100) + (mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()));
            datos[1] = String.valueOf(mDF.format((((mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes()) * mC.getIVA()) /100) + (mDP_CE.getTotalKwHora() * mC.getPrecioKW_Mes())));
            TablaCostosTotalesCE.addRow(datos);
            
            if(mBD.AgregarCostoConsumoElectrico(mDP_CE, MenuCotizacion.Clave))
            {
                //SE MODIFICA O SE AÑADE EL COSTO DE PRODUCCION
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existe una falla en la Base de Datos");
            }
            
        }
        else
        {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumoElectrico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsumoElectrico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AgregarCostoProduccion;
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_PreciosProduccion;
    private javax.swing.JButton BTN_Reporte;
    private javax.swing.JTable TBL_ConsumoElectrico;
    private javax.swing.JTable TBL_MostrarProducto;
    private javax.swing.JTable TBL_TotalesCE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
