/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Cotizacion;

import BaseDeDatos.*;
import Clases.*;
import Formularios.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardogarciadelgado
 */
public final class ElegirProducto extends javax.swing.JFrame {
    
    DefaultTableModel Tabla = new DefaultTableModel()
    {
        @Override
        public boolean isCellEditable(int row, int column) 
        {
            return false;
        }
    };
    BD_1 mBD;
    Producto mProducto;
    MenuCotizacion mMC;
    int Seleccion;
    public static String Clave;
    public static String NombreProducto;

    /**
     * Creates new form ElegirProducto
     */
    public ElegirProducto() {
        initComponents();
        Tabla.addColumn("Clave");
        Tabla.addColumn("Nombre");
        Tabla.addColumn("Descripcion");
        Tabla.addColumn("Precio");
        mBD = null;
        mProducto = null;
        mMC = null;
        LlenarTabla();
        Seleccion = 0;
        LBL_Clave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Productos = new javax.swing.JTable();
        TXT_Search = new javax.swing.JTextField();
        LBL_Clave = new javax.swing.JLabel();
        BTN_Atras2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cotizacion");

        TBL_Productos.setModel(Tabla);
        TBL_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_ProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_Productos);

        TXT_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_SearchKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_SearchKeyReleased(evt);
            }
        });

        LBL_Clave.setText("Clave");

        BTN_Atras2.setText("Atrás");
        BTN_Atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Atras2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_Atras2)
                            .addComponent(jLabel1)
                            .addComponent(TXT_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_Clave))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Atras2)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBL_Clave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_SearchKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXT_SearchKeyTyped

    private void TXT_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_SearchKeyReleased
        // TODO add your handling code here:
        LlenarTablaFiltro();
    }//GEN-LAST:event_TXT_SearchKeyReleased

    private void TBL_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_ProductosMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_Productos.rowAtPoint(evt.getPoint());
        Clave = TBL_Productos.getModel().getValueAt(Seleccion, 0).toString();
        NombreProducto = TBL_Productos.getModel().getValueAt(Seleccion, 1).toString();
        mMC = new MenuCotizacion();
        mMC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TBL_ProductosMouseClicked

    private void BTN_Atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Atras2ActionPerformed
        // TODO add your handling code here:
        if ("1".equals(Login.Tipousuario))
        {
            Admin mA = new Admin();
            mA.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            if ("2".equals(Login.Tipousuario))
            {
                Cotizador mC = new Cotizador();
                mC.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                if ("3".equals(Login.Tipousuario))
                {
                    Ventas mV = new Ventas();
                    mV.setVisible(true);
                    this.setVisible(false);
                }
                else
                {                   
                }
            }
        }        
    }//GEN-LAST:event_BTN_Atras2ActionPerformed
    
    public void LlenarTabla()
    {
        mBD = new BD_1();
        mProducto = new Producto();
        
        ArrayList mListaProducto = mBD.ConsultaProductos();
        String [] datos=null;

        for (Object mListaProducto2 : mListaProducto)
        {
            datos = new String[4];
            mProducto = (Producto) mListaProducto2;

            //datos[0] = String.valueOf(mProducto.getIdProducto());
            datos[0] = mProducto.getClave();
            datos[1] = mProducto.getNombreProducto();
            datos[2] = mProducto.getDescripcion();
            datos[3] = String.valueOf(mProducto.getPrecioUnitaro());
            Tabla.addRow(datos);
        }
        this.TBL_Productos = new javax.swing.JTable();
        this.TBL_Productos.setModel(Tabla);
        this.TBL_Productos.getColumnModel().getColumn(0).setPreferredWidth(10);
        this.TBL_Productos.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_Productos.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_Productos.getColumnModel().getColumn(2).setPreferredWidth(50);
        if (this.TBL_Productos.getRowCount() > 0) 
        {
            this.TBL_Productos.setRowSelectionInterval(0, 0);
        }
    }
    
    public void LlenarTablaFiltro()
    {
        LimpiarTabla();
        mBD = new BD_1();
        mProducto = new Producto();
        
        ArrayList mListaProducto = mBD.ConsultaProductosFiltro(TXT_Search.getText());
        String [] datos=null;

        for (Object mListaProducto2 : mListaProducto)
        {
            datos = new String[4];
            mProducto = (Producto) mListaProducto2;

            //datos[0] = String.valueOf(mProducto.getIdProducto());
            datos[0] = mProducto.getClave();
            datos[1] = mProducto.getNombreProducto();
            datos[2] = mProducto.getDescripcion();
            datos[3] = String.valueOf(mProducto.getPrecioUnitaro());
            Tabla.addRow(datos);
        }
        this.TBL_Productos = new javax.swing.JTable();
        this.TBL_Productos.setModel(Tabla);
        this.TBL_Productos.getColumnModel().getColumn(0).setPreferredWidth(10);
        this.TBL_Productos.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.TBL_Productos.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_Productos.getColumnModel().getColumn(2).setPreferredWidth(50);
        if (this.TBL_Productos.getRowCount() > 0) 
        {
            this.TBL_Productos.setRowSelectionInterval(0, 0);
        }
    }
    
    public void LimpiarTabla()
    {
        Tabla = (DefaultTableModel) TBL_Productos.getModel();
        int a = Tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirProducto().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Atras2;
    private javax.swing.JLabel LBL_Clave;
    private javax.swing.JTable TBL_Productos;
    private javax.swing.JTextField TXT_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
