/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Cotizacion;

/**
 *
 * @author eduardogarciadelgado
 */
public final class MenuCotizacion extends javax.swing.JFrame {
    /**
     * Creates new form MenuCotizacion
     */
    ElegirProducto mEP;
    PreciosProduccion mPP;
    ConsumoElectrico mCE;
    ReporteCostos mRC;
    public static String Clave;
    public static String NombreProducto;
    
    public MenuCotizacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cotizador Encinales");
        mPP = null;
        mEP = null;
        mCE = null;
        mRC = null;
        LBL_NomProducto.setText("Cotizacion de producto " + ElegirProducto.Clave + " " + ElegirProducto.NombreProducto);
        Clave = ElegirProducto.Clave;
        NombreProducto = ElegirProducto.NombreProducto;
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTN_PrecProduccion = new javax.swing.JButton();
        BTN_PrecConsElec = new javax.swing.JButton();
        BTN_Reporte = new javax.swing.JButton();
        LBL_NomProducto = new javax.swing.JLabel();
        BTN_Atras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BTN_PrecProduccion.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_PrecProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/produccion (1).png"))); // NOI18N
        BTN_PrecProduccion.setText("Producción");
        BTN_PrecProduccion.setBorderPainted(false);
        BTN_PrecProduccion.setContentAreaFilled(false);
        BTN_PrecProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_PrecProduccion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/factory(1).png"))); // NOI18N
        BTN_PrecProduccion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/factory(1).png"))); // NOI18N
        BTN_PrecProduccion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/factory(1).png"))); // NOI18N
        BTN_PrecProduccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_PrecProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PrecProduccionActionPerformed(evt);
            }
        });

        BTN_PrecConsElec.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_PrecConsElec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enchufe (1).png"))); // NOI18N
        BTN_PrecConsElec.setText("Consumo Eléctrico");
        BTN_PrecConsElec.setBorderPainted(false);
        BTN_PrecConsElec.setContentAreaFilled(false);
        BTN_PrecConsElec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_PrecConsElec.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enchufe (2).png"))); // NOI18N
        BTN_PrecConsElec.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enchufe (2).png"))); // NOI18N
        BTN_PrecConsElec.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enchufe (2).png"))); // NOI18N
        BTN_PrecConsElec.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enchufe-inteligente (1).png"))); // NOI18N
        BTN_PrecConsElec.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTN_PrecConsElec.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_PrecConsElec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PrecConsElecActionPerformed(evt);
            }
        });

        BTN_Reporte.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/analitica.png"))); // NOI18N
        BTN_Reporte.setText("Reporte de Costes");
        BTN_Reporte.setBorderPainted(false);
        BTN_Reporte.setContentAreaFilled(false);
        BTN_Reporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_Reporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/analitica (1).png"))); // NOI18N
        BTN_Reporte.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/analitica (1).png"))); // NOI18N
        BTN_Reporte.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/analitica (1).png"))); // NOI18N
        BTN_Reporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ReporteActionPerformed(evt);
            }
        });

        LBL_NomProducto.setFont(new java.awt.Font("Sukhumvit Set", 0, 24)); // NOI18N

        BTN_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (3).png"))); // NOI18N
        BTN_Atras.setBorderPainted(false);
        BTN_Atras.setContentAreaFilled(false);
        BTN_Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/003.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 24)); // NOI18N
        jLabel1.setText("Selecciona alguna de las siguientes opciones");

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 0, 28)); // NOI18N
        jLabel2.setText("Variables a Cotizar");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Opciones de Producción");

        jLabel4.setText("Seleccionar Cantidad de Materia Prima");

        jLabel5.setText("Unidad de Medida");

        jLabel6.setText("Elemento de Costo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("Cuanto Personal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setText("Precio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_Atras)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel2)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(LBL_NomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTN_PrecConsElec, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_PrecProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LBL_NomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_PrecProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_PrecConsElec, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_Reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        mEP = new ElegirProducto();
        mEP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void BTN_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ReporteActionPerformed
        // TODO add your handling code here:
        mRC = new ReporteCostos();
        mRC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_ReporteActionPerformed

    private void BTN_PrecConsElecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PrecConsElecActionPerformed
        // TODO add your handling code here:
        mCE = new ConsumoElectrico();
        mCE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_PrecConsElecActionPerformed

    private void BTN_PrecProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PrecProduccionActionPerformed
        // TODO add your handling code here:
        mPP = new PreciosProduccion();
        mPP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_PrecProduccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCotizacion().setVisible(true);
            }
        });
    }

    /**
     *
     */
    public javax.swing.JLabel LBL_NombreProducto;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_PrecConsElec;
    private javax.swing.JButton BTN_PrecProduccion;
    private javax.swing.JButton BTN_Reporte;
    private javax.swing.JLabel LBL_NomProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
