/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Cotizacion;

import BaseDeDatos.BD_1;
import BaseDeDatos.*;
import Clases.*;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardogarciadelgado
 */
public final class PreciosProduccion extends javax.swing.JFrame {
    
    /**
     * Creates new form PreciosProduccion
     */
    MenuCotizacion mMC;
    BD_1 mBD;
    Produccion mP;
    Constantes mC;
    DP_Produccion mDP_P;
    PreciosProduccion_1 mPP_1;
    ConsumoElectrico mCE;
    ReporteCostos mRC;
    
    DefaultTableModel TablaProducto;
    DefaultTableModel TablaProduccion;
    DefaultTableModel TablaCostosProduccion;
    
    DecimalFormat mDF;
    
    int idModificarPrecioProduccion;
    int Seleccion;
    
    public PreciosProduccion() 
            
    {
                this.TablaProducto = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return (row == 0) && (column==2);
            }
        };
        this.TablaProduccion = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        this.TablaCostosProduccion = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cotizador Encinales");
        
        TablaProducto.addColumn("Clave");
        TablaProducto.addColumn("Nombre");
        
        TablaProduccion.addColumn("ID");
        TablaProduccion.addColumn("Cantidad");
        TablaProduccion.addColumn("Unidad de Medida");
        TablaProduccion.addColumn("Elementos de Costo");
        TablaProduccion.addColumn("Personal por Area");
        TablaProduccion.addColumn("Precio Unitario");
        TablaProduccion.addColumn("Precio");
        
        TablaCostosProduccion.addColumn("Costo por unidad");
        TablaCostosProduccion.addColumn("Costo");
        
        mMC = null;
        mBD = null;
        mP = null;
        mPP_1 = null;
        mC = null;
        mDP_P = null;
        mCE = null;
        mRC = null;
        mDF = new DecimalFormat("#.#####");
        mDF.setRoundingMode(RoundingMode.CEILING);
        LlenarTablaProducto();
        LlenarTablaPreciosProduccion();
        LlenarTablaCostoProduccion();
        idModificarPrecioProduccion = 0;
        Seleccion = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_MostrarProducto = new javax.swing.JTable();
        BTN_Atras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_PreciosProduccion = new javax.swing.JTable();
        BTN_AgregarCostoProduccion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBL_CostosProduccion = new javax.swing.JTable();
        BTN_ConsumoElectrico = new javax.swing.JButton();
        BTN_Reporte = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 22)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/humanpictos (1).png"))); // NOI18N
        jLabel1.setText(" Determinación Costos De Producción");

        TBL_MostrarProducto.setModel(TablaProducto);
        jScrollPane1.setViewportView(TBL_MostrarProducto);

        BTN_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (3).png"))); // NOI18N
        BTN_Atras.setBorderPainted(false);
        BTN_Atras.setContentAreaFilled(false);
        BTN_Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        TBL_PreciosProduccion.setModel(TablaProduccion);
        TBL_PreciosProduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_PreciosProduccionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBL_PreciosProduccion);

        BTN_AgregarCostoProduccion.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_AgregarCostoProduccion.setText("Añadir Datos de Producción");
        BTN_AgregarCostoProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AgregarCostoProduccionActionPerformed(evt);
            }
        });

        TBL_CostosProduccion.setModel(TablaCostosProduccion);
        jScrollPane3.setViewportView(TBL_CostosProduccion);

        BTN_ConsumoElectrico.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_ConsumoElectrico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enchufe (3).png"))); // NOI18N
        BTN_ConsumoElectrico.setText("Ir a Consumo Electrico");
        BTN_ConsumoElectrico.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_ConsumoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConsumoElectricoActionPerformed(evt);
            }
        });

        BTN_Reporte.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/estadistica.png"))); // NOI18N
        BTN_Reporte.setText("Ir a Reporte de Costos");
        BTN_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ReporteActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/003.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_AgregarCostoProduccion)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTN_Atras)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_ConsumoElectrico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_Reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BTN_ConsumoElectrico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_AgregarCostoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        mMC = new MenuCotizacion();
        mMC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void BTN_AgregarCostoProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AgregarCostoProduccionActionPerformed
        // TODO add your handling code here:
        PreciosProduccion_1.Bandera = false;
        mPP_1 = new PreciosProduccion_1();
        mPP_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AgregarCostoProduccionActionPerformed

    private void TBL_PreciosProduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_PreciosProduccionMouseClicked
        // TODO add your handling code here:
        Seleccion = TBL_PreciosProduccion.rowAtPoint(evt.getPoint());
        PreciosProduccion_1.idPrecioProd = Integer.parseInt(TBL_PreciosProduccion.getModel().getValueAt(Seleccion, 0).toString());
        PreciosProduccion_1.Cantidad = Double.parseDouble(TBL_PreciosProduccion.getModel().getValueAt(Seleccion, 1).toString());
        PreciosProduccion_1.UnidadMedida = TBL_PreciosProduccion.getModel().getValueAt(Seleccion, 2).toString();
        PreciosProduccion_1.ElementoCosto = TBL_PreciosProduccion.getModel().getValueAt(Seleccion, 3).toString();
        PreciosProduccion_1.Personal = Integer.parseInt(TBL_PreciosProduccion.getModel().getValueAt(Seleccion, 4).toString());
        PreciosProduccion_1.PrecioUnitario = Double.parseDouble(TBL_PreciosProduccion.getModel().getValueAt(Seleccion, 5).toString());
        PreciosProduccion_1.Bandera = true;
        mPP_1 = new PreciosProduccion_1();
        mPP_1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TBL_PreciosProduccionMouseClicked

    private void BTN_ConsumoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConsumoElectricoActionPerformed
        // TODO add your handling code here:
        mCE = new ConsumoElectrico();
        mCE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_ConsumoElectricoActionPerformed

    private void BTN_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ReporteActionPerformed
        // TODO add your handling code here:
        mRC = new ReporteCostos();
        mRC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_ReporteActionPerformed

    public void LlenarTablaProducto()
    {
        String[] Datos = new String[3];
        Datos[0] = MenuCotizacion.Clave;
        Datos[1] = MenuCotizacion.NombreProducto;        
        TablaProducto.addRow(Datos);
    }
    
    public void LlenarTablaPreciosProduccion()
    {
        mBD = new BD_1();
        mP = new Produccion();
        
        ArrayList mListaPreciosProduccion = mBD.ConsultaPreciosProduccion(MenuCotizacion.Clave);
        String [] datos;       

        for (Object mListaProducto2 : mListaPreciosProduccion)
        {
            datos = new String[7];
            mP = (Produccion) mListaProducto2;

            datos[0] = String.valueOf(mP.getIdProduccion());
            datos[1] = String.valueOf(mP.getCantidad());
            datos[2] = mP.getUnidadMedida();
            datos[3] = mP.getElementoCosto();
            datos[4] = String.valueOf(mP.getPersonal());
            datos[5] = String.valueOf(mP.getPrecioUnit());
            datos[6] = String.valueOf(mDF.format(mP.getPrecioCantidad()));
            TablaProduccion.addRow(datos);
        }
        this.TBL_PreciosProduccion = new javax.swing.JTable();
        this.TBL_PreciosProduccion.setModel(TablaProduccion);
        this.TBL_PreciosProduccion.getColumnModel().getColumn(0).setPreferredWidth(10);
        this.TBL_PreciosProduccion.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.TBL_PreciosProduccion.getColumnModel().getColumn(2).setPreferredWidth(50);
        this.TBL_PreciosProduccion.getColumnModel().getColumn(3).setPreferredWidth(50);
        this.TBL_PreciosProduccion.getColumnModel().getColumn(4).setPreferredWidth(50);
        this.TBL_PreciosProduccion.getColumnModel().getColumn(5).setPreferredWidth(50);
        this.TBL_PreciosProduccion.getColumnModel().getColumn(6).setPreferredWidth(50);
        if (this.TBL_PreciosProduccion.getRowCount() > 0) 
        {
            this.TBL_PreciosProduccion.setRowSelectionInterval(0, 0);
        }
    }
    
    public void LlenarTablaCostoProduccion()
    {
        mBD = new BD_1();
        mP = new Produccion();
        mC = new Constantes();
        String [] datos;
        ArrayList mListaConstantes = mBD.ConsultaConstantes();
        
        for (Object mListaConstantes2 : mListaConstantes)
        {
            mC = (Constantes) mListaConstantes2;
        }       
        
        if (TablaProduccion.getRowCount() != 0)
        {
            mDP_P = new DP_Produccion();           
            datos = new String[2];
            
            datos[0] = "Costo Total Unitario";
            mDP_P.setCostoUnitOperativo(mBD.SumarPreciosProduccion(MenuCotizacion.Clave));
            datos[1] = String.valueOf(mDF.format(mDP_P.getCostoUnitOperativo()));
            TablaCostosProduccion.addRow(datos);
            
            datos[0] = "Costo Unitario Operativo";
            datos[1] = String.valueOf(mC.getCostoUnitOp());
            TablaCostosProduccion.addRow(datos);
            
            datos[0] = "Costo Total de la Venta";
            mDP_P.setCostoTotalVenta(mC.getCostoUnitOp() + mDP_P.getCostoUnitOperativo());           
            datos[1] = String.valueOf(mDF.format(mDP_P.getCostoTotalVenta()));
            TablaCostosProduccion.addRow(datos);
            
            datos[0] = "Utilidad";
            mDP_P.setUtilidad((mDP_P.getCostoTotalVenta() * mC.getUtilidad()) / 100);
            datos[1] = String.valueOf(mDF.format(mDP_P.getUtilidad()));
            TablaCostosProduccion.addRow(datos);
            
            datos[0] = "Precio Venta sin IVA";
            mDP_P.setPrecioSinIVA(mDP_P.getUtilidad() + mDP_P.getCostoTotalVenta());
            datos[1] = String.valueOf(mDF.format(mDP_P.getPrecioSinIVA()));
            TablaCostosProduccion.addRow(datos);
            
            datos[0] = "Precio Venta con IVA";
            mDP_P.setPrecioConIVA(((mDP_P.getPrecioSinIVA() * mC.getIVA()) / 100) + mDP_P.getPrecioSinIVA());
            datos[1] = String.valueOf(mDF.format(mDP_P.getPrecioConIVA()));
            TablaCostosProduccion.addRow(datos);
            
            if(mBD.AgregarCostoProduccion(mDP_P, MenuCotizacion.Clave))
            {
                //SE MODIFICA O SE AÑADE EL COSTO DE PRODUCCION
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existe una falla en la Base de Datos");
            }
            
        }
        else
        {
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreciosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreciosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreciosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreciosProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreciosProduccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AgregarCostoProduccion;
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_ConsumoElectrico;
    private javax.swing.JButton BTN_Reporte;
    private javax.swing.JTable TBL_CostosProduccion;
    private javax.swing.JTable TBL_MostrarProducto;
    private javax.swing.JTable TBL_PreciosProduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
