/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Cotizacion;

import BaseDeDatos.*;
import Clases.*;
import Formularios.Cotizacion.Reporte.*;
import Formularios.*;
import java.awt.Image;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author eduardogarciadelgado
 */
public class ReporteCostos extends javax.swing.JFrame 
{        
    MenuCotizacion mMenuC;
    BD_1 mBD;
    Constantes mC;
    DP_Produccion mDPP;
    ClaseReporteCostos mRC;
    ConexionReporte mConRep;
    ConsumoElectrico mCE;
    PreciosProduccion mPP;
    
    double CostoMateriaPrima;
    double CMP;
    
    double TiempoMdO;
    
    double CostoOpMdo;
    
    double CE;
    double COpCE;
    
    double CostoMP;
    double CostoEE;
    double CostoMdO;
    double CostoAd;
    double CostoFEmb;
    
    double PrecioFinalSugerido;
    
    DecimalFormat mDF;
    /**
     * Creates new form ReporteCostos
     */
    public ReporteCostos() {
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cotizador Encinales");
        jLabel1.setText("Reporte de Costos de  " + ElegirProducto.Clave + " - " + ElegirProducto.NombreProducto);
        
        mMenuC = null;
        mBD = null;
        mC = null;
        mDPP = null;
        mRC = null;
        mConRep = null;
        mCE = null;
        mPP = null;
        
        CostoMateriaPrima = 0;
        CMP = 0;
        
        TiempoMdO = 0;
        CostoOpMdo = 0;
        
        CE = 0;
        COpCE = 0;
        
        PrecioFinalSugerido = 0;
        
        CostoMP = 0;
        CostoEE = 0;
        CostoMdO = 0;
        CostoAd = 0;
        CostoFEmb = 0;
        
        mDF = new DecimalFormat("#.####");
        
        LlenarCamposMateriaPrima();
        LlenarCamposManoDeObra();
        LlenarCamposMaquinaHerramientas();
        LlenarDeterminadoCostes();
        LlenarGrafico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane2 = new java.awt.ScrollPane();
        jPanel1 = new javax.swing.JPanel();
        BTN_Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXT_Especificaciones = new javax.swing.JTextField();
        TXT_CostoMateriaPrima = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXT_DiametroNominal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TXT_PesoMaterial = new javax.swing.JTextField();
        TXT_CMP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TXT_UnidadEmpaque = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TXT_UnidadUtilizacionM2 = new javax.swing.JTextField();
        TXT_UnidadUtilizacionKg = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TXT_Merma = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TXT_TiempoMdO = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TXT_COpMdO = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TXT_CE = new javax.swing.JTextField();
        TXT_COpCE = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        TXT_CMPFinal = new javax.swing.JTextField();
        TXT_CEEFinal = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        TXT_CMdOFinal = new javax.swing.JTextField();
        TXT_CAdmin = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        TXT_CFEmb = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        LBL_Utilidad = new javax.swing.JLabel();
        LBL_IVA = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        TXT_PrecioFinal = new javax.swing.JTextField();
        TXT_IVA = new javax.swing.JTextField();
        TXT_Utilidad = new javax.swing.JTextField();
        TXT_CTOp = new javax.swing.JTextField();
        BTN_PDF = new javax.swing.JButton();
        BTN_ConsumoElectrico = new javax.swing.JButton();
        BTN_PreciosProduccion = new javax.swing.JButton();
        LBL_Grafica = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BTN_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/flecha-hacia-la-izquierda (3).png"))); // NOI18N
        BTN_Atras.setBorderPainted(false);
        BTN_Atras.setContentAreaFilled(false);
        BTN_Atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (2).png"))); // NOI18N
        BTN_Atras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/espalda (1).png"))); // NOI18N
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sukhumvit Set", 0, 22)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/grafico.png"))); // NOI18N
        jLabel1.setText("Reporte de Costos");

        jLabel8.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel8.setText("- Materia Prima");

        jLabel9.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel9.setText("Especificaciones del material");

        TXT_CostoMateriaPrima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_CostoMateriaPrimaKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel17.setText("Costo materia prima  ($)");

        jLabel10.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel10.setText("Diametro nominal (mm)");

        TXT_DiametroNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_DiametroNominalActionPerformed(evt);
            }
        });
        TXT_DiametroNominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_DiametroNominalKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel11.setText("Peso del material (kg/m)");

        TXT_PesoMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_PesoMaterialKeyTyped(evt);
            }
        });

        TXT_CMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_CMPKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel19.setText("Costo total operativo ($)");

        TXT_UnidadEmpaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_UnidadEmpaqueActionPerformed(evt);
            }
        });
        TXT_UnidadEmpaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_UnidadEmpaqueKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel12.setText("Unidad de empaque (m)");

        jLabel13.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel13.setText("Unidades de utilización (m^2)");

        TXT_UnidadUtilizacionM2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_UnidadUtilizacionM2KeyTyped(evt);
            }
        });

        TXT_UnidadUtilizacionKg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_UnidadUtilizacionKgKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel14.setText("Unidades de utilización (kg)");

        jLabel15.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel15.setText("Merma c/1pz (g) ");

        TXT_Merma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_MermaKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel20.setText("- Maquinas y Herramientas");

        jLabel23.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel23.setText("Tiempo mano de obra (h)");

        jLabel27.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel27.setText("C. operativo mano de obra ($)");

        jLabel28.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel28.setText("- Mano de Obra");

        jLabel30.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel30.setText("C. operativo energético ($)");

        jLabel29.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel29.setText("Consumo energético (kw/h)");

        jLabel31.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel31.setText("- Discrimado de Costos");

        jLabel32.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        jLabel32.setText("Item");

        jLabel33.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel33.setText("1. Costo materia prima ($)");

        TXT_CMPFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_CMPFinalActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel34.setText("2. Costo energía eléctrica ($)");

        jLabel35.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel35.setText("3. Costo mano de obra ($)");

        jLabel36.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel36.setText("4. Costo administrativo ($)");

        jLabel37.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel37.setText("5. Costo flete embarque ($)");

        jLabel38.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel38.setText("Costo Total Operativo ($)");

        LBL_Utilidad.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        LBL_Utilidad.setText("Utilidad 30%");

        LBL_IVA.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        LBL_IVA.setText("IVA 16%");

        jLabel41.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("PRECIO SUGERIDO DE VENTA ($)");

        TXT_PrecioFinal.setForeground(new java.awt.Color(255, 0, 0));
        TXT_PrecioFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_PrecioFinalActionPerformed(evt);
            }
        });

        TXT_CTOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_CTOpActionPerformed(evt);
            }
        });

        BTN_PDF.setFont(new java.awt.Font("Sukhumvit Set", 0, 14)); // NOI18N
        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pdf.png"))); // NOI18N
        BTN_PDF.setText("  Generar Reporte");
        BTN_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PDFActionPerformed(evt);
            }
        });

        BTN_ConsumoElectrico.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_ConsumoElectrico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enchufe (3).png"))); // NOI18N
        BTN_ConsumoElectrico.setText("Ir a Consumo Electrico");
        BTN_ConsumoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConsumoElectricoActionPerformed(evt);
            }
        });

        BTN_PreciosProduccion.setFont(new java.awt.Font("Sukhumvit Set", 0, 18)); // NOI18N
        BTN_PreciosProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/factory_1.png"))); // NOI18N
        BTN_PreciosProduccion.setText("Ir a Precios de Produccion");
        BTN_PreciosProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PreciosProduccionActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/003.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTN_Atras)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_PreciosProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_ConsumoElectrico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel27))
                                            .addComponent(jLabel23))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TXT_COpMdO, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXT_TiempoMdO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel35)
                                                    .addComponent(jLabel34)
                                                    .addComponent(jLabel36))
                                                .addGap(39, 39, 39))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel33)
                                                    .addComponent(jLabel37)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TXT_CEEFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXT_CMPFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXT_CMdOFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXT_CAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXT_CFEmb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(63, 63, 63)
                                        .addComponent(TXT_CostoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(34, 34, 34)
                                        .addComponent(TXT_UnidadUtilizacionM2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(70, 70, 70)
                                        .addComponent(TXT_DiametroNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel28)
                                .addGap(378, 378, 378)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(TXT_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29)
                                    .addComponent(LBL_IVA)
                                    .addComponent(LBL_Utilidad))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_Utilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_COpCE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_Merma, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_UnidadEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_Especificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_CTOp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_UnidadUtilizacionKg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_PesoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_CMP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LBL_Grafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTN_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_Atras)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTN_ConsumoElectrico)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_PreciosProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXT_PesoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TXT_UnidadUtilizacionKg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(TXT_CMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)))
                        .addGap(25, 25, 25)
                        .addComponent(LBL_Grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel10))
                                    .addComponent(TXT_DiametroNominal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(TXT_UnidadUtilizacionM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(TXT_CostoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(TXT_Especificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_UnidadEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_Merma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(TXT_TiempoMdO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(TXT_COpMdO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(TXT_CMPFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(TXT_CEEFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(TXT_CMdOFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(TXT_CAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(TXT_CFEmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41)
                                    .addComponent(TXT_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXT_CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXT_COpCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(TXT_CTOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXT_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBL_IVA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXT_Utilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBL_Utilidad))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        
        MenuCotizacion mMenuC = new MenuCotizacion();
        this.dispose();
        mMenuC.setVisible(true);
      
        
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void TXT_UnidadEmpaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_UnidadEmpaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_UnidadEmpaqueActionPerformed

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed
        // TODO add your handling code here:
        String DescripcionN = "El usuario " + Login.NombreUsuario + " creó o modificó datos de un reporte de cotización";
        mBD.AgregarRegistro(DescripcionN);
        mBD.Desconectar();
        try {
            SubirActualizarReporte();
        } catch (JRException ex) {
            Logger.getLogger(ReporteCostos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_ConsumoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConsumoElectricoActionPerformed
        // TODO add your handling code here:
        mCE = new ConsumoElectrico();
        mCE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_ConsumoElectricoActionPerformed

    private void BTN_PreciosProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PreciosProduccionActionPerformed
        // TODO add your handling code here:
        mPP = new PreciosProduccion();
        mPP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_PreciosProduccionActionPerformed

    private void TXT_PrecioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_PrecioFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_PrecioFinalActionPerformed

    private void TXT_CMPFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_CMPFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_CMPFinalActionPerformed

    private void TXT_DiametroNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_DiametroNominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_DiametroNominalActionPerformed

    private void TXT_CTOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_CTOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_CTOpActionPerformed

    private void TXT_DiametroNominalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_DiametroNominalKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_DiametroNominal.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_DiametroNominal.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_DiametroNominalKeyTyped

    private void TXT_UnidadUtilizacionM2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_UnidadUtilizacionM2KeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_UnidadUtilizacionM2.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_UnidadUtilizacionM2.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_UnidadUtilizacionM2KeyTyped

    private void TXT_CostoMateriaPrimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_CostoMateriaPrimaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_CostoMateriaPrima.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_CostoMateriaPrima.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_CostoMateriaPrimaKeyTyped

    private void TXT_UnidadEmpaqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_UnidadEmpaqueKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_UnidadEmpaque.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_UnidadEmpaque.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_UnidadEmpaqueKeyTyped

    private void TXT_MermaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_MermaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_Merma.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_Merma.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_MermaKeyTyped

    private void TXT_PesoMaterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_PesoMaterialKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_PesoMaterial.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_PesoMaterial.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_PesoMaterialKeyTyped

    private void TXT_UnidadUtilizacionKgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_UnidadUtilizacionKgKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_UnidadUtilizacionKg.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_UnidadUtilizacionKg.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_UnidadUtilizacionKgKeyTyped

    private void TXT_CMPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_CMPKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }

        if (TXT_CMP.getText().length() == 10) {
            evt.consume();
        }

        if (evt.getKeyChar() == '.' && TXT_CMP.getText().contains(".")) {
            evt.consume();
        }

        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_TXT_CMPKeyTyped

    /**
     */
    
    public void LlenarCamposMateriaPrima()
    {
        mBD = new BD_1();
        
        CostoMateriaPrima = mBD.ConsultarCostoMateriaPrima(MenuCotizacion.Clave);
        CMP = mBD.ConsultarCostoUnitOp(MenuCotizacion.Clave);
        
        if((CostoMateriaPrima != 0) && (CMP != 0))
        {
            TXT_CostoMateriaPrima.setText(String.valueOf(mDF.format(CostoMateriaPrima)));
            TXT_CMP.setText(String.valueOf(mDF.format(CMP)));
            
            TXT_CostoMateriaPrima.setEnabled(false);
            TXT_CMP.setEnabled(false);
        }
        else
        {
            TXT_CostoMateriaPrima.setText("0");
            TXT_CMP.setText("0");
        }
        
    }
    
    public void LlenarCamposManoDeObra()
    {
        mBD = new BD_1();
        
        TiempoMdO = mBD.ConsultarTiempos(MenuCotizacion.Clave,true);
        CostoOpMdo = mBD.ConsultarTiempos(MenuCotizacion.Clave,false);

        if((CostoOpMdo != 0))
        {
            TXT_TiempoMdO.setText(String.valueOf(mDF.format(TiempoMdO)));
            TXT_COpMdO.setText(String.valueOf(mDF.format(CostoOpMdo)));
            
            TXT_TiempoMdO.setEnabled(false);
            TXT_COpMdO.setEnabled(false);
        }
        else
        {
            TXT_TiempoMdO.setText("0");
            TXT_COpMdO.setText("0");
        }
        
    }
    
    public void LlenarCamposMaquinaHerramientas()
    {
        mBD = new BD_1();
        
        CE = mBD.SumarConsumosElectricos(MenuCotizacion.Clave);
        COpCE = mBD.ConsultaCostoOpoConsumoElectrico(MenuCotizacion.Clave);

        if((CE != 0) && (COpCE != 0))
        {
            TXT_CE.setText(String.valueOf(mDF.format(CE)));
            TXT_COpCE.setText(String.valueOf(mDF.format(COpCE)));
            
            TXT_CE.setEnabled(false);
            TXT_COpCE.setEnabled(false);
        }
        else
        {
            TXT_CE.setText("0");
            TXT_COpCE.setText("0");
        }       
    }
    
    public void LlenarDeterminadoCostes()
    {
        if (TXT_CMP.getText() != null)
        {
            TXT_CMPFinal.setText(TXT_CMP.getText());
            TXT_CMPFinal.setEnabled(false);
            CostoMP = Double.parseDouble(TXT_CMPFinal.getText());
        }
        
        if (TXT_COpCE.getText() != null)
        {
            TXT_CEEFinal.setText(TXT_COpCE.getText());
            TXT_CEEFinal.setEnabled(false);  
            CostoEE = Double.parseDouble(TXT_CEEFinal.getText());
        }
        
        if (TXT_COpMdO.getText() != null)
        {
            TXT_CMdOFinal.setText(TXT_COpMdO.getText());
            TXT_CMdOFinal.setEnabled(false);
            CostoMdO = Double.parseDouble(TXT_CMdOFinal.getText());
        }
        
        mC = new Constantes();
        ArrayList mListaConstantes = mBD.ConsultaConstantes();
        
        for (Object mListaConstantes2 : mListaConstantes)
        {
            mC = (Constantes) mListaConstantes2;
        }
        
        TXT_CAdmin.setText(String.valueOf(mC.getCostoUnitOp() / 2));
        TXT_CFEmb.setText(String.valueOf(mC.getCostoUnitOp() / 2));
        CostoAd = Double.parseDouble(TXT_CAdmin.getText());
        CostoFEmb = Double.parseDouble(TXT_CFEmb.getText());
        TXT_CAdmin.setEnabled(false);
        TXT_CFEmb.setEnabled(false);
        
        mDPP = new DP_Produccion();
        ArrayList mListaPreciosProduccion = mBD.ConsultaDeterminacionPreciosProduccion(MenuCotizacion.Clave);
        
        for (Object mListaPreciosProduccion2 : mListaPreciosProduccion)
        {
            mDPP = (DP_Produccion) mListaPreciosProduccion2;
        }
        
        TXT_CTOp.setText(String.valueOf(mDF.format(mDPP.getCostoTotalVenta())));
        TXT_Utilidad.setText(String.valueOf(mDF.format(mDPP.getUtilidad())));
        TXT_IVA.setText(String.valueOf(mDF.format( (mDPP.getPrecioConIVA()) - (mDPP.getPrecioSinIVA()) )));
        
        PrecioFinalSugerido = (mDPP.getCostoTotalVenta()) + (mDPP.getUtilidad()) + ( (mDPP.getPrecioConIVA()) - (mDPP.getPrecioSinIVA()) );
        TXT_PrecioFinal.setText(mDF.format(PrecioFinalSugerido));
        
        TXT_CTOp.setEnabled(false);
        TXT_Utilidad.setEnabled(false);
        TXT_IVA.setEnabled(false);
        TXT_PrecioFinal.setEnabled(false);                      
    }
    
    public void LlenarGrafico()
    {   
        DefaultPieDataset mDPDS = new DefaultPieDataset();
        
        mDPDS.setValue("Materia Prima", CostoMP);
        mDPDS.setValue("Energía Eléctrica", CostoEE);  
        mDPDS.setValue("Mano de obra", CostoMdO);
        mDPDS.setValue("Administrativo", CostoAd);  
        mDPDS.setValue("Flete Embarque", CostoFEmb); //true,true,false
        
        JFreeChart jFC = ChartFactory.createPieChart("% Participación en costos", mDPDS, true, false, false);
        try 
        {
            OutputStream png = new FileOutputStream("Grafico.png");
            ChartUtilities.writeBufferedImageAsPNG(png, jFC.createBufferedImage(400, 400));
            png.close();
        } 
        catch (IOException e) 
        {

        }
        String urlImagen = "Grafico.png";
        ImageIcon img = new ImageIcon(urlImagen);
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(LBL_Grafica.getWidth(), LBL_Grafica.getHeight(), Image.SCALE_DEFAULT));
        LBL_Grafica.setIcon(icon);
        this.repaint();
    }
    
    public void SubirActualizarReporte() throws JRException
    {
        mRC = new ClaseReporteCostos();
        mBD = new BD_1();
        if ( ("".equals(TXT_Especificaciones.getText()))  
                || ("".equals(TXT_DiametroNominal.getText())) || ("".equals(TXT_PesoMaterial.getText())) 
                || ("".equals(TXT_UnidadEmpaque.getText())) || ("".equals(TXT_UnidadUtilizacionM2.getText())) 
                || ("".equals(TXT_UnidadUtilizacionKg.getText())) || ("".equals(TXT_Merma.getText())))
        {                  
            JOptionPane.showMessageDialog(null, "Llenar los campos necesarios");
        }
        else
        {                                   
            ValidarCajasReporte();
            
            mRC.setEspecificaciones(TXT_Especificaciones.getText());
            mRC.setDiametro(Double.parseDouble(TXT_DiametroNominal.getText()));
            mRC.setPesoMaterial(Double.parseDouble(TXT_PesoMaterial.getText()));
            mRC.setUnidadEmpaque(Double.parseDouble(TXT_UnidadEmpaque.getText()));
            mRC.setUnidadUtilizacionM(Double.parseDouble(TXT_UnidadUtilizacionM2.getText()));
            mRC.setUnidadUtilizacionKg(Double.parseDouble(TXT_UnidadUtilizacionKg.getText()));
            mRC.setMerma(Double.parseDouble(TXT_Merma.getText()));
            mRC.setCMatPrim(Double.parseDouble(TXT_CostoMateriaPrima.getText()));
            mRC.setCMatPrimTotal(Double.parseDouble(TXT_CMP.getText()));
            mRC.setTManoDeObra(Double.parseDouble(TXT_TiempoMdO.getText()));
            mRC.setCOpTotal(Double.parseDouble(TXT_COpMdO.getText()));
            mRC.setConsEnerKWh(Double.parseDouble(TXT_CE.getText()));
            mRC.setConsEnerPesos(Double.parseDouble(TXT_COpCE.getText()));
            mRC.setCostoAdmin(Double.parseDouble(TXT_CAdmin.getText()));
            mRC.setCostoFleteEmbarq(Double.parseDouble(TXT_CFEmb.getText()));
            mRC.setCostoTotalOp(Double.parseDouble(TXT_CTOp.getText()));
            mRC.setUtilidad(Double.parseDouble(TXT_Utilidad.getText()));
            mRC.setIVA(Double.parseDouble(TXT_IVA.getText()));
            mRC.setPrecioSugerido(Double.parseDouble(TXT_PrecioFinal.getText()));

            if((mBD.AgregarReportes(mRC, MenuCotizacion.Clave)) 
                    && (mBD.ActualizarPrecioProducto(MenuCotizacion.Clave, (Double.parseDouble(TXT_PrecioFinal.getText())))))
            {
                
                //SE MODIFICA O SE AÑADE EL COSTO DE PRODUCCION
                //BD_1 mBDN = new BD_1();
                //mBDN.ActualizarPrecioProducto(MenuCotizacion.Clave, (Double.parseDouble(TXT_PrecioFinal.getText())));
                
                CallReport mCR = new CallReport();
                mConRep = new ConexionReporte();
                mBD = new BD_1();
                Map Parametros = new HashMap();
                
                Parametros.put("Producto_idProducto", mBD.ConsultarIdProductoClave(MenuCotizacion.Clave));
                //Parametros.put("graficobarra", getClass().getClassLoader().getResourceAsStream("Grafico.png"));
                mBD.Conectar();
                //mCR.abrirReporte("src/ReporteCostos.jrxml", mBD.getConnection(), Parametros);
                mCR.abrirReporte("ReporteCostos.jasper", mBD.getConnection(), Parametros);
                mBD.Desconectar();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existe una falla en la base de datos y no se puede agregar el reporte");
            }           
        }
    }
    
    public void ValidarCajasReporte()
    {
        if (("n/a".equals(TXT_DiametroNominal.getText())))
        {
            TXT_DiametroNominal.setText("0");
        }
        else
        {
            
        }
        if (("n/a".equals(TXT_PesoMaterial.getText())))
        {
            TXT_PesoMaterial.setText("0");
        }
        else
        {
            
        }

        if (("n/a".equals(TXT_UnidadEmpaque.getText())))
        {
            TXT_UnidadEmpaque.setText("0");
        }
        else
        {
            
        }
        if (("n/a".equals(TXT_UnidadUtilizacionM2.getText())))
        {
            TXT_UnidadUtilizacionM2.setText("0");
        }
        else
        {
            
        }

        if (("n/a".equals(TXT_UnidadUtilizacionKg.getText())))
        {
            TXT_UnidadUtilizacionKg.setText("0");
        }
        else
        {
            
        }
        if (("n/a".equals(TXT_Merma.getText())))
        {
            TXT_Merma.setText("0");
        }
        else
        {
            
        }
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteCostos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_ConsumoElectrico;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_PreciosProduccion;
    private javax.swing.JLabel LBL_Grafica;
    private javax.swing.JLabel LBL_IVA;
    private javax.swing.JLabel LBL_Utilidad;
    private javax.swing.JTextField TXT_CAdmin;
    private javax.swing.JTextField TXT_CE;
    private javax.swing.JTextField TXT_CEEFinal;
    private javax.swing.JTextField TXT_CFEmb;
    private javax.swing.JTextField TXT_CMP;
    private javax.swing.JTextField TXT_CMPFinal;
    private javax.swing.JTextField TXT_CMdOFinal;
    private javax.swing.JTextField TXT_COpCE;
    private javax.swing.JTextField TXT_COpMdO;
    private javax.swing.JTextField TXT_CTOp;
    private javax.swing.JTextField TXT_CostoMateriaPrima;
    private javax.swing.JTextField TXT_DiametroNominal;
    private javax.swing.JTextField TXT_Especificaciones;
    private javax.swing.JTextField TXT_IVA;
    private javax.swing.JTextField TXT_Merma;
    private javax.swing.JTextField TXT_PesoMaterial;
    private javax.swing.JTextField TXT_PrecioFinal;
    private javax.swing.JTextField TXT_TiempoMdO;
    private javax.swing.JTextField TXT_UnidadEmpaque;
    private javax.swing.JTextField TXT_UnidadUtilizacionKg;
    private javax.swing.JTextField TXT_UnidadUtilizacionM2;
    private javax.swing.JTextField TXT_Utilidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.ScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables
}