/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Cotizacion;

import BaseDeDatos.*;
import Clases.*;
import Formularios.Cotizacion.Reporte.*;
import java.awt.Image;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author eduardogarciadelgado
 */
public class ReporteCostos extends javax.swing.JFrame 
{        
    MenuCotizacion mMenuC;
    BD_1 mBD;
    Constantes mC;
    DP_Produccion mDPP;
    ClaseReporteCostos mRC;
    ConexionReporte mConRep;
    ConsumoElectrico mCE;
    PreciosProduccion mPP;
    
    double CostoMateriaPrima;
    double CMP;
    
    double TiempoMdO;
    
    double CostoOpMdo;
    
    double CE;
    double COpCE;
    
    double CostoMP;
    double CostoEE;
    double CostoMdO;
    double CostoAd;
    double CostoFEmb;
    
    double PrecioFinalSugerido;
    
    DecimalFormat mDF;
    /**
     * Creates new form ReporteCostos
     */
    public ReporteCostos() {
        initComponents();
        jLabel1.setText("REPORTE DE COSTOS DE " + ElegirProducto.Clave + " - " + ElegirProducto.NombreProducto);
        
        mMenuC = null;
        mBD = null;
        mC = null;
        mDPP = null;
        mRC = null;
        mConRep = null;
        mCE = null;
        mPP = null;
        
        CostoMateriaPrima = 0;
        CMP = 0;
        
        TiempoMdO = 0;
        CostoOpMdo = 0;
        
        CE = 0;
        COpCE = 0;
        
        PrecioFinalSugerido = 0;
        
        CostoMP = 0;
        CostoEE = 0;
        CostoMdO = 0;
        CostoAd = 0;
        CostoFEmb = 0;
        
        mDF = new DecimalFormat("#.####");
        
        LlenarCamposMateriaPrima();
        LlenarCamposManoDeObra();
        LlenarCamposMaquinaHerramientas();
        LlenarDeterminadoCostes();
        LlenarGrafico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane2 = new java.awt.ScrollPane();
        BTN_Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXT_Especificaciones = new javax.swing.JTextField();
        TXT_CostoMateriaPrima = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXT_DiametroNominal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TXT_PesoMaterial = new javax.swing.JTextField();
        TXT_CMP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TXT_UnidadEmpaque = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TXT_UnidadUtilizacionM2 = new javax.swing.JTextField();
        TXT_UnidadUtilizacionKg = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TXT_Merma = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TXT_TiempoMdO = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TXT_COpMdO = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TXT_CE = new javax.swing.JTextField();
        TXT_COpCE = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        TXT_CMPFinal = new javax.swing.JTextField();
        TXT_CEEFinal = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        TXT_CMdOFinal = new javax.swing.JTextField();
        TXT_CAdmin = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        TXT_CFEmb = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        LBL_Utilidad = new javax.swing.JLabel();
        LBL_IVA = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        TXT_PrecioFinal = new javax.swing.JTextField();
        TXT_IVA = new javax.swing.JTextField();
        TXT_Utilidad = new javax.swing.JTextField();
        TXT_CTOp = new javax.swing.JTextField();
        Panel_Oculto = new javax.swing.JPanel();
        LBL_Grafica = new javax.swing.JLabel();
        BTN_PDF = new javax.swing.JButton();
        BTN_ConsumoElectrico = new javax.swing.JButton();
        BTN_PreciosProduccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_Atras.setText("Atras");
        BTN_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("REPORTE DE COSTOS");

        jLabel8.setText("MATERIA PRIMA");

        jLabel9.setText("Especificaciones del material");

        jLabel17.setText("Costo materia prima  ($)");

        jLabel10.setText("Diametro nominal (mm)");

        jLabel11.setText("Peso del material (kg/m)");

        jLabel19.setText("Costo total operativo ($)");

        TXT_UnidadEmpaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_UnidadEmpaqueActionPerformed(evt);
            }
        });

        jLabel12.setText("Unidad de empaque (m)");

        jLabel13.setText("Unidades de utilización (m^2)");

        jLabel14.setText("Unidades de utilización (kg)");

        jLabel15.setText("Merma c/1pz (g) ");

        jLabel20.setText("MANO DE OBRA");

        jLabel23.setText("Tiempo mano de obra (h)");

        jLabel27.setText("C. operativo mano de obra ($)");

        jLabel28.setText("MAQUINAS Y HERRAMIENTAS");

        jLabel30.setText("C. operativo energético ($)");

        jLabel29.setText("Consumo energético (kw/h)");

        jLabel31.setText("DISCRIMINADO DE COSTES");

        jLabel32.setText("ITEM");

        jLabel33.setText("1. Costo materia prima ($)");

        jLabel34.setText("2. Costo energía eléctrica ($)");

        jLabel35.setText("3. Costo mano de obra ($)");

        jLabel36.setText("4. Costo administrativo ($)");

        jLabel37.setText("5. Costo flete embarque ($)");

        jLabel38.setText("Costo Total Operativo ($)");

        LBL_Utilidad.setText("Utilidad 30%");

        LBL_IVA.setText("IVA 16%");

        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("PRECIO SUGERIDO DE VENTA ($)");

        TXT_PrecioFinal.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout Panel_OcultoLayout = new javax.swing.GroupLayout(Panel_Oculto);
        Panel_Oculto.setLayout(Panel_OcultoLayout);
        Panel_OcultoLayout.setHorizontalGroup(
            Panel_OcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_OcultoLayout.createSequentialGroup()
                .addComponent(LBL_Grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_OcultoLayout.setVerticalGroup(
            Panel_OcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_OcultoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL_Grafica, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
        );

        BTN_PDF.setText("PDF");
        BTN_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PDFActionPerformed(evt);
            }
        });

        BTN_ConsumoElectrico.setText("Ir a Consumo Electrico");
        BTN_ConsumoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConsumoElectricoActionPerformed(evt);
            }
        });

        BTN_PreciosProduccion.setText("Ir a Precios de Produccion");
        BTN_PreciosProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PreciosProduccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(418, 418, 418))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_Atras)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addComponent(BTN_PreciosProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_ConsumoElectrico)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBL_IVA)
                                            .addComponent(jLabel41)
                                            .addComponent(LBL_Utilidad)
                                            .addComponent(jLabel38))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel36)
                                                .addComponent(jLabel33))
                                            .addGap(65, 65, 65)))
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXT_PrecioFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(TXT_Utilidad)
                                    .addComponent(TXT_CTOp)
                                    .addComponent(TXT_CFEmb)
                                    .addComponent(TXT_CAdmin)
                                    .addComponent(TXT_CMdOFinal)
                                    .addComponent(TXT_CEEFinal)
                                    .addComponent(TXT_CMPFinal)
                                    .addComponent(TXT_COpCE)
                                    .addComponent(TXT_CE)
                                    .addComponent(TXT_IVA, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Panel_Oculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTN_PDF))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(412, 412, 412))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(366, 366, 366))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(86, 86, 86))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(136, 136, 136)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_Merma, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_UnidadUtilizacionKg, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_UnidadUtilizacionM2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_UnidadEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TXT_TiempoMdO, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel27))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(200, 200, 200)
                                                .addComponent(jLabel19))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TXT_Especificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TXT_PesoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TXT_DiametroNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXT_CostoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXT_CMP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXT_COpMdO, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Atras)
                    .addComponent(jLabel1)
                    .addComponent(BTN_ConsumoElectrico)
                    .addComponent(BTN_PreciosProduccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(TXT_CostoMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXT_Especificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXT_DiametroNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(TXT_CMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TXT_PesoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TXT_UnidadEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TXT_UnidadUtilizacionM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(TXT_UnidadUtilizacionKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TXT_Merma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_TiempoMdO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27)
                    .addComponent(TXT_COpMdO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(TXT_CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_COpCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_CMPFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_CEEFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_CMdOFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_CAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_CFEmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(TXT_CTOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_Utilidad)
                            .addComponent(TXT_Utilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_IVA)
                            .addComponent(TXT_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Panel_Oculto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(TXT_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_PDF))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AtrasActionPerformed
        // TODO add your handling code here:
        mMenuC = new MenuCotizacion();
        mMenuC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_AtrasActionPerformed

    private void TXT_UnidadEmpaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_UnidadEmpaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_UnidadEmpaqueActionPerformed

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed
        // TODO add your handling code here:
        SubirActualizarReporte();

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_ConsumoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConsumoElectricoActionPerformed
        // TODO add your handling code here:
        mCE = new ConsumoElectrico();
        mCE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_ConsumoElectricoActionPerformed

    private void BTN_PreciosProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PreciosProduccionActionPerformed
        // TODO add your handling code here:
        mPP = new PreciosProduccion();
        mPP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_PreciosProduccionActionPerformed

    /**
     */
    
    public void LlenarCamposMateriaPrima()
    {
        mBD = new BD_1();
        
        CostoMateriaPrima = mBD.ConsultarCostoMateriaPrima(MenuCotizacion.Clave);
        CMP = mBD.ConsultarCostoUnitOp(MenuCotizacion.Clave);
        
        if((CostoMateriaPrima != 0) && (CMP != 0))
        {
            TXT_CostoMateriaPrima.setText(String.valueOf(mDF.format(CostoMateriaPrima)));
            TXT_CMP.setText(String.valueOf(mDF.format(CMP)));
            
            TXT_CostoMateriaPrima.setEnabled(false);
            TXT_CMP.setEnabled(false);
        }
        else
        {
            TXT_CostoMateriaPrima.setText("0");
            TXT_CMP.setText("0");
        }
        
    }
    
    public void LlenarCamposManoDeObra()
    {
        mBD = new BD_1();
        
        TiempoMdO = mBD.ConsultarTiempos(MenuCotizacion.Clave,true);
        CostoOpMdo = mBD.ConsultarTiempos(MenuCotizacion.Clave,false);

        if((CostoOpMdo != 0))
        {
            TXT_TiempoMdO.setText(String.valueOf(mDF.format(TiempoMdO)));
            TXT_COpMdO.setText(String.valueOf(mDF.format(CostoOpMdo)));
            
            TXT_TiempoMdO.setEnabled(false);
            TXT_COpMdO.setEnabled(false);
        }
        else
        {
            TXT_TiempoMdO.setText("0");
            TXT_COpMdO.setText("0");
        }
        
    }
    
    public void LlenarCamposMaquinaHerramientas()
    {
        mBD = new BD_1();
        
        CE = mBD.SumarConsumosElectricos(MenuCotizacion.Clave);
        COpCE = mBD.ConsultaCostoOpoConsumoElectrico(MenuCotizacion.Clave);

        if((CE != 0) && (COpCE != 0))
        {
            TXT_CE.setText(String.valueOf(mDF.format(CE)));
            TXT_COpCE.setText(String.valueOf(mDF.format(COpCE)));
            
            TXT_CE.setEnabled(false);
            TXT_COpCE.setEnabled(false);
        }
        else
        {
            TXT_CE.setText("0");
            TXT_COpCE.setText("0");
        }       
    }
    
    public void LlenarDeterminadoCostes()
    {
        if (TXT_CMP.getText() != null)
        {
            TXT_CMPFinal.setText(TXT_CMP.getText());
            TXT_CMPFinal.setEnabled(false);
            CostoMP = Double.parseDouble(TXT_CMPFinal.getText());
        }
        
        if (TXT_COpCE.getText() != null)
        {
            TXT_CEEFinal.setText(TXT_COpCE.getText());
            TXT_CEEFinal.setEnabled(false);  
            CostoEE = Double.parseDouble(TXT_CEEFinal.getText());
        }
        
        if (TXT_COpMdO.getText() != null)
        {
            TXT_CMdOFinal.setText(TXT_COpMdO.getText());
            TXT_CMdOFinal.setEnabled(false);
            CostoMdO = Double.parseDouble(TXT_CMdOFinal.getText());
        }
        
        mC = new Constantes();
        ArrayList mListaConstantes = mBD.ConsultaConstantes();
        
        for (Object mListaConstantes2 : mListaConstantes)
        {
            mC = (Constantes) mListaConstantes2;
        }
        
        TXT_CAdmin.setText(String.valueOf(mC.getCostoUnitOp() / 2));
        TXT_CFEmb.setText(String.valueOf(mC.getCostoUnitOp() / 2));
        CostoAd = Double.parseDouble(TXT_CAdmin.getText());
        CostoFEmb = Double.parseDouble(TXT_CFEmb.getText());
        TXT_CAdmin.setEnabled(false);
        TXT_CFEmb.setEnabled(false);
        
        mDPP = new DP_Produccion();
        ArrayList mListaPreciosProduccion = mBD.ConsultaDeterminacionPreciosProduccion(MenuCotizacion.Clave);
        
        for (Object mListaPreciosProduccion2 : mListaPreciosProduccion)
        {
            mDPP = (DP_Produccion) mListaPreciosProduccion2;
        }
        
        TXT_CTOp.setText(String.valueOf(mDF.format(mDPP.getCostoTotalVenta())));
        TXT_Utilidad.setText(String.valueOf(mDF.format(mDPP.getUtilidad())));
        TXT_IVA.setText(String.valueOf(mDF.format( (mDPP.getPrecioConIVA()) - (mDPP.getPrecioSinIVA()) )));
        
        PrecioFinalSugerido = (mDPP.getCostoTotalVenta()) + (mDPP.getUtilidad()) + ( (mDPP.getPrecioConIVA()) - (mDPP.getPrecioSinIVA()) );
        TXT_PrecioFinal.setText(mDF.format(PrecioFinalSugerido));
        
        TXT_CTOp.setEnabled(false);
        TXT_Utilidad.setEnabled(false);
        TXT_IVA.setEnabled(false);
        TXT_PrecioFinal.setEnabled(false);                      
    }
    
    public void LlenarGrafico()
    {   
        DefaultPieDataset mDPDS = new DefaultPieDataset();
        
        mDPDS.setValue("Materia Prima", CostoMP);
        mDPDS.setValue("Energía Eléctrica", CostoEE);  
        mDPDS.setValue("Mano de obra", CostoMdO);
        mDPDS.setValue("Administrativo", CostoAd);  
        mDPDS.setValue("Flete Embarque", CostoFEmb); //true,true,false
        
        JFreeChart jFC = ChartFactory.createPieChart("% Participación en costos", mDPDS, true, false, false);
        try 
        {
            OutputStream png = new FileOutputStream("Grafico.png");
            ChartUtilities.writeBufferedImageAsPNG(png, jFC.createBufferedImage(400, 400));
            png.close();
        } 
        catch (IOException e) 
        {

        }
        String urlImagen = "Grafico.png";
        ImageIcon img = new ImageIcon(urlImagen);
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(LBL_Grafica.getWidth(), LBL_Grafica.getHeight(), Image.SCALE_DEFAULT));
        LBL_Grafica.setIcon(icon);
        this.repaint();
    }
    
    public void SubirActualizarReporte()
    {
        mRC = new ClaseReporteCostos();
        mBD = new BD_1();
        if ( ("".equals(TXT_Especificaciones.getText()))  
                || ("".equals(TXT_DiametroNominal.getText())) || ("".equals(TXT_PesoMaterial.getText())) 
                || ("".equals(TXT_UnidadEmpaque.getText())) || ("".equals(TXT_UnidadUtilizacionM2.getText())) 
                || ("".equals(TXT_UnidadUtilizacionKg.getText())) || ("".equals(TXT_Merma.getText())))
        {                  
            JOptionPane.showMessageDialog(null, "Llena bien los campos");
        }
        else
        {                                   
            ValidarCajasReporte();
            
            mRC.setEspecificaciones(TXT_Especificaciones.getText());
            mRC.setDiametro(Double.parseDouble(TXT_DiametroNominal.getText()));
            mRC.setPesoMaterial(Double.parseDouble(TXT_PesoMaterial.getText()));
            mRC.setUnidadEmpaque(Double.parseDouble(TXT_UnidadEmpaque.getText()));
            mRC.setUnidadUtilizacionM(Double.parseDouble(TXT_UnidadUtilizacionM2.getText()));
            mRC.setUnidadUtilizacionKg(Double.parseDouble(TXT_UnidadUtilizacionKg.getText()));
            mRC.setMerma(Double.parseDouble(TXT_Merma.getText()));
            mRC.setCMatPrim(Double.parseDouble(TXT_CostoMateriaPrima.getText()));
            mRC.setCMatPrimTotal(Double.parseDouble(TXT_CMP.getText()));
            mRC.setTManoDeObra(Double.parseDouble(TXT_TiempoMdO.getText()));
            mRC.setCOpTotal(Double.parseDouble(TXT_COpMdO.getText()));
            mRC.setConsEnerKWh(Double.parseDouble(TXT_CE.getText()));
            mRC.setConsEnerPesos(Double.parseDouble(TXT_COpCE.getText()));
            mRC.setCostoAdmin(Double.parseDouble(TXT_CAdmin.getText()));
            mRC.setCostoFleteEmbarq(Double.parseDouble(TXT_CFEmb.getText()));
            mRC.setCostoTotalOp(Double.parseDouble(TXT_CTOp.getText()));
            mRC.setUtilidad(Double.parseDouble(TXT_Utilidad.getText()));
            mRC.setIVA(Double.parseDouble(TXT_IVA.getText()));
            mRC.setPrecioSugerido(Double.parseDouble(TXT_PrecioFinal.getText()));

            if(mBD.AgregarReportes(mRC, MenuCotizacion.Clave))
            {
                //SE MODIFICA O SE AÑADE EL COSTO DE PRODUCCION
                //JOptionPane.showMessageDialog(null, "Archivo exitoso");
                
                CallReport mCR = new CallReport();
                mConRep = new ConexionReporte();
                mBD = new BD_1();

                Map Parametros = new HashMap();
                Parametros.put("Producto_idProducto", mBD.ConsultarIdProductoClave(MenuCotizacion.Clave));
                mBD.Conectar();
                mCR.abrirReporte("src/Formularios/Cotizacion/Reporte/ReporteCostos.jrxml", mBD.getConnection(), Parametros);
                mBD.Desconectar();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existe una falla en la Base de Datos");
            }           
        }
    }
    
    public void ValidarCajasReporte()
    {
        if (("n/a".equals(TXT_DiametroNominal.getText())))
        {
            TXT_DiametroNominal.setText("0");
        }
        else
        {
            
        }
        if (("n/a".equals(TXT_PesoMaterial.getText())))
        {
            TXT_PesoMaterial.setText("0");
        }
        else
        {
            
        }

        if (("n/a".equals(TXT_UnidadEmpaque.getText())))
        {
            TXT_UnidadEmpaque.setText("0");
        }
        else
        {
            
        }
        if (("n/a".equals(TXT_UnidadUtilizacionM2.getText())))
        {
            TXT_UnidadUtilizacionM2.setText("0");
        }
        else
        {
            
        }

        if (("n/a".equals(TXT_UnidadUtilizacionKg.getText())))
        {
            TXT_UnidadUtilizacionKg.setText("0");
        }
        else
        {
            
        }
        if (("n/a".equals(TXT_Merma.getText())))
        {
            TXT_Merma.setText("0");
        }
        else
        {
            
        }
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteCostos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Atras;
    private javax.swing.JButton BTN_ConsumoElectrico;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_PreciosProduccion;
    private javax.swing.JLabel LBL_Grafica;
    private javax.swing.JLabel LBL_IVA;
    private javax.swing.JLabel LBL_Utilidad;
    private javax.swing.JPanel Panel_Oculto;
    private javax.swing.JTextField TXT_CAdmin;
    private javax.swing.JTextField TXT_CE;
    private javax.swing.JTextField TXT_CEEFinal;
    private javax.swing.JTextField TXT_CFEmb;
    private javax.swing.JTextField TXT_CMP;
    private javax.swing.JTextField TXT_CMPFinal;
    private javax.swing.JTextField TXT_CMdOFinal;
    private javax.swing.JTextField TXT_COpCE;
    private javax.swing.JTextField TXT_COpMdO;
    private javax.swing.JTextField TXT_CTOp;
    private javax.swing.JTextField TXT_CostoMateriaPrima;
    private javax.swing.JTextField TXT_DiametroNominal;
    private javax.swing.JTextField TXT_Especificaciones;
    private javax.swing.JTextField TXT_IVA;
    private javax.swing.JTextField TXT_Merma;
    private javax.swing.JTextField TXT_PesoMaterial;
    private javax.swing.JTextField TXT_PrecioFinal;
    private javax.swing.JTextField TXT_TiempoMdO;
    private javax.swing.JTextField TXT_UnidadEmpaque;
    private javax.swing.JTextField TXT_UnidadUtilizacionKg;
    private javax.swing.JTextField TXT_UnidadUtilizacionM2;
    private javax.swing.JTextField TXT_Utilidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.ScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables
}